objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>doctorsSurgery</fullName>
        <active>true</active>
        <label>Doctors Surgery</label>
    </recordTypes>
</CustomObject>

objects/Campaign.object
<CustomObject>
    <sharingModel>FullAccess</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is for the relation between Opp and Campaign.
Robin S. 22.02.2019</description>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Für diese Opportunity kann keine Kampagne erstellt werden</errorMessage>
            <filterItems>
                <field>Opportunity.RecordTypeId</field>
                <operation>equals</operation>
                <value>Substitute Doctor, Substitute Caregiver, Recruitment Doctor, Recruitment Caregiver</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/CompetenceDoctorAccount__c.object
<CustomObject>
    <label>Kompetenz Arzt Account</label>
    <nameField>
        <label>Competence Docotor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kompetenz Arzt Account</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Diese Kompetenz ist nur für Arzt-Accounts erlaubt</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Doctor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Kompetenz Arzt Account</relationshipLabel>
        <relationshipName>Kompetenzen</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MedicalDiscipline__c</fullName>
        <label>Medical Discipline</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Fachbereich</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>QualificationLevel__c</fullName>
        <label>Qualification Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assistenzarzt</fullName>
                </value>
                <value>
                    <fullName>Facharzt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/QualificationDoctor__c.object
<CustomObject>
    <label>Qualifikation Arzt</label>
    <nameField>
        <label>Competence Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Qualifikationen Arzt</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Dies ist nur für &apos;Vertretung Arzt&apos; möglich</errorMessage>
            <filterItems>
                <field>Opportunity.RecordTypeId</field>
                <operation>equals</operation>
                <value>Substitute Doctor, Recruitment Doctor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Qualification Doctor</relationshipLabel>
        <relationshipName>Qualifications_Doctor</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MedicalDiscipline__c</fullName>
        <description>NEW Field for speciality
Because the old field don&apos;t use the global value set.
Robin S. 20.06.2019</description>
        <label>Ⓜ️ Medical Discipline</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Fachbereich</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>QualificationLevel__c</fullName>
        <label>Ⓜ️ Qualification Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assistenzarzt</fullName>
                </value>
                <value>
                    <fullName>Facharzt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/SearchPreset__mdt.object
<CustomObject>
    <description>Search Presets for doctor and care givers</description>
    <label>Search Preset</label>
    <pluralLabel>Search Preset</pluralLabel>
    <fields>
        <fullName>MedicalDiscipline__c</fullName>
        <label>Medical Discipline</label>
        <length>1024</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

classes/TKQueryLayerTest.cls
@isTest
public class TKQueryLayerTest {
    static testMethod void getOpportunityByCampaignIdTest() {
        Id rtype = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('doctorsSurgery').getRecordTypeId();
        Account a = new Account(Name='Name',
                                RecordTypeId=rtype);
        insert a;
        
        Id oppoRtype = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Recruitment Doctor').getRecordTypeId();
        Opportunity o = new Opportunity(Name='OPPO',
                                        StageName='New',
                                        CloseDate=System.Today(),
                                        RecordTypeId=oppoRtype,
                                        AccountId=a.Id
                                       );
        insert o;

        Campaign c = new Campaign(Name='Test',
                                  Opportunity__c = o.Id);
        insert c;

        QualificationDoctor__c dq = new QualificationDoctor__c(Name='Test',
                                                               Opportunity__c = o.Id);
        dq.MedicalDiscipline__c = 'Allgemeinchirurgie';
        dq.QualificationLevel__c = 'Facharzt';
        insert dq;

        Opportunity actual = TKQueryLayer.getOpportunityByCampaignId(c.Id);
        System.assert(actual != null);
    }
    
    static testMethod void getCandidateByIdTest() {
        Id rtype = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('doctor').getRecordTypeId();
        Account candidate = new Account(LastName='Name',
                                        FirstName='Name',
		                                RecordTypeId=rtype);
        insert candidate;


        CompetenceDoctorAccount__c cda = new CompetenceDoctorAccount__c();
        cda.Name = 'CDA';
        cda.Account__c = candidate.Id;
        cda.MedicalDiscipline__c = 'Allgemeinchirurgie';
        cda.QualificationLevel__c = 'Facharzt';
        insert cda;

        Account actual = TKQueryLayer.getCandidateById(candidate.Id);
        System.assert(actual != null);
    }

    static testMethod void getSearchPresetsTest() {
        List<SearchPreset__mdt> actual = TKQueryLayer.getSearchPresets();
        System.assert(actual != null);
        System.assertEquals(actual.size(), 26);
    }
}