objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>RadiusKm__c</fullName>
        <label>Radius km</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>50</fullName>
                </value>
                <value>
                    <fullName>100</fullName>
                </value>
                <value>
                    <fullName>150</fullName>
                </value>
                <value>
                    <fullName>200</fullName>
                </value>
                <value>
                    <fullName>Deutschlandweit</fullName>
                </value>
                <value>
                    <fullName>300</fullName>
                    <isActive>false</isActive>
                    <label>300</label>
                </value>
                <value>
                    <fullName>Schweizweit</fullName>
                    <isActive>false</isActive>
                    <label>Schweizweit</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Company_Car__c</fullName>
        <description>Information about a PersonAccount.
Robin S. 07.06.2019</description>
        <label>Company Car</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PreferredCity__c</fullName>
        <description>Preferred city is specified here. This field is used to search for the surrounding area.
Robin S. - 22.01.2019</description>
        <label>Preferred City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>doctari_client__c</fullName>
        <label>doctari client</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RequestedStateCanton__c</fullName>
        <label>Requested State / Canton</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RequestedStateCanton</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

objects/OperatingTime__c.object
<CustomObject>
    <label>Einsatzzeitraum</label>
    <nameField>
        <displayFormat>OT-{00000}</displayFormat>
        <label>Einsatzzeit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Einsatzzeiträume</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Referenz zum erstellten Vertragsentwurf; wird automatisch ausgefüllt.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Operation Time</relationshipLabel>
        <relationshipName>OperationTime</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>doctari_client__c</fullName>
        <description>references the doctari client field from contract via process for reporting</description>
        <label>doctari client</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Quote.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>BC_100__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>die Person erhält eine BahnCard 100</inlineHelpText>
        <label>BC 100</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <inlineHelpText>Notwendige Informationen für die Vertragserstellungen können hier hinterlegt werden. Diese Informationen werden ebenfalls nach L1 übertragen.</inlineHelpText>
        <label>Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Own_car__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>die Person nutzt ihren eigenen PKW</inlineHelpText>
        <label>Own car</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PLZArea__c</fullName>
        <label>PLZ Area</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PLZ_Gebiet</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Radiuskm__c</fullName>
        <inlineHelpText>definiert das Einsatzgebiet nach dem Umkreis in km um den angegebenen Ort</inlineHelpText>
        <label>Radius km</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Radius_km</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Entry_date__c</fullName>
        <inlineHelpText>Vertragsbeginn</inlineHelpText>
        <label>Entry date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Company_car__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>die Person erhält einen Firmenwagen</inlineHelpText>
        <label>Company car</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hourly_rate__c</fullName>
        <inlineHelpText>Brutto-Verdienst pro Stunde in €</inlineHelpText>
        <label>Hourly rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RecruitingAs__c</fullName>
        <inlineHelpText>Berufsbezeichnung entsprechend Urkunde/Qualifikationsnachweis, die sich aus der Kompetenz der Person ergibt; diese kann bearbeitet werden</inlineHelpText>
        <label>Recruiting As</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PreferredCity__c</fullName>
        <inlineHelpText>definiert das Einsatzgebiet nach einem Ort in Kombination mit dem Feld “Umkreis in km”</inlineHelpText>
        <label>Preferred City</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MailingAddress__c</fullName>
        <formula>IF(ISBLANK(Person_Account__r.MailingAddressCo__c),&quot;&quot;,Person_Account__r.MailingAddressCo__c + &quot;, &quot;) +
Person_Account__r.PersonContact.MailingStreet + &quot;, &quot; +
Person_Account__r.PersonContact.MailingPostalCode + &quot;, &quot; +
Person_Account__r.PersonContact.MailingCity + &quot;, &quot; +
Person_Account__r.PersonContact.MailingCountry</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>gibt die Postanschrift der Person wieder, mit dem der Vertrag geschlossen werden soll</inlineHelpText>
        <label>Mailing Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name der Person, mit der ein Vertrag geschlossen werden soll</inlineHelpText>
        <label>Person Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Doctor, Caregiver</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>doctari_client__c</fullName>
        <description>Is needed for Landwehr.
Robin S. 14.10.2019</description>
        <label>doctari client</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>doctari Fachpflege GmbH</fullName>
                </value>
                <value>
                    <fullName>doctari Pflege ANÜ GmbH</fullName>
                </value>
                <value>
                    <fullName>doctari Ärzte ANÜ GmbH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>limitation_type__c</fullName>
        <inlineHelpText>Art der Befristung</inlineHelpText>
        <label>limitation type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>unlimited</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FurtherEducation__c</fullName>
        <label>Further Education</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pflege_Weiterbildungen</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>gross_monthly_fee__c</fullName>
        <description>Entering working hours per week and a hourly rate, will calculate that field</description>
        <formula>WorkingHoursPerYear__c * Hourly_rate__c / 12</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>berechnetes Feld: Stundensatz * Arbeitsstunden pro Jahr / 12 Monate</inlineHelpText>
        <label>gross monthly fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OtherPersonalAddress__c</fullName>
        <inlineHelpText>hier kann eine alternative Adresse zum Feld “Adresse Personal” hinterlegt werden</inlineHelpText>
        <label>Other Personal Address</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RequestedStateCanton__c</fullName>
        <inlineHelpText>definiert das Einsatzgebiet nach Bundesländern</inlineHelpText>
        <label>Requested State Canton</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RequestedStateCanton</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_area_in_facility__c</fullName>
        <inlineHelpText>beschreibt die Tätigkeit, für die die Person eingesetzt werden soll</inlineHelpText>
        <label>Work area (in facility)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>working_hours_per_month__c</fullName>
        <description>The working hours per year are divided through 12 months to calculate the hours per month</description>
        <formula>WorkingHoursPerYear__c / 12</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>berechnetes Feld: Arbeitsstunden pro Jahr / 12 Monate</inlineHelpText>
        <label>working hours per month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Creation_of_contract_Employee__c</fullName>
        <inlineHelpText>Art des Vertrages</inlineHelpText>
        <label>Creation of contract Personal</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Arbeitsvertrag Fachpfleger</fullName>
                </value>
                <value>
                    <fullName>Änderungsvertrag Arbeitsvertrag Fachpfleger</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Reisekosten__c.object
<CustomObject>
    <label>Reisekosten</label>
    <nameField>
        <label>Reisekosten Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reisekosten</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Traveling Costs</relationshipLabel>
        <relationshipName>Traveling_Costs</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

classes/QuoteQueryLayer.cls
public with sharing class QuoteQueryLayer extends SObjectQueryLayer {
    @TestVisible
    protected override Schema.SObjectType getSObjectType() {
            return Quote.sObjectType;
    }

    @AuraEnabled(Cacheable=true)
    public static Quote getQuotebyId(String recordId) {
            return [
                SELECT Id, QuoteNumber, Name,doctari_client__c, Person_Account__r.Name, Creation_of_contract_Employee__c, limitation_type__c, Entry_date__c, RecruitingAs__c, FurtherEducation__c, Work_area_in_facility__c, RequestedStateCanton__c, PLZArea__c, PreferredCity__c, Radiuskm__c, working_hours_per_month__c, Hourly_rate__c, gross_monthly_fee__c, Company_car__c, BC_100__c, Own_car__c, MailingAddress__c, OtherPersonalAddress__c, Comment__c, Owner.Name, CreatedBy.Name, LastModifiedBy.Name 
                FROM Quote 
                WHERE Id = :recordId
            ];
    }

    @AuraEnabled(Cacheable=true)
    public static Quote getQuoteWithRelatedListsbyId(String recordId) {
            return [
                SELECT Id, 
                (SELECT Id, Quote__c FROM Traveling_Costs__r WHERE Quote__c = :recordId),
                (SELECT Id, Quote__c FROM OperationTime__r WHERE Quote__c = :recordId),
                (SELECT Id, QuoteId FROM QuoteLineItems WHERE QuoteId = :recordId)
                FROM Quote 
                WHERE Id = :recordId
            ];
    }
}