objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>EconomicRegion__c</fullName>
        <label>Economic Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>unbekannt</fullName>
                </value>
                <value>
                    <fullName>EU/EWR/CH</fullName>
                </value>
                <value>
                    <fullName>Drittstaat</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Dokumente__c.object
<CustomObject>
    <label>Unterlagen</label>
    <nameField>
        <label>Dokumente Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unterlagen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dokumente</relationshipLabel>
        <relationshipName>Dokumente</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ValidUntil__c</fullName>
        <label>Valid Until</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TypeOfDocument__c</fullName>
        <label>Type Of Document</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>AccountType__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>A1-Bescheinigung</fullName>
                </value>
                <value>
                    <fullName>Abfrage Vorarbeitgeber</fullName>
                </value>
                <value>
                    <fullName>Abschlussvollmacht Rahmenvertrag Ärzte ANÜ</fullName>
                </value>
                <value>
                    <fullName>Abschlussvollmacht Rahmenvertrag Ärzte ANÜ + MED ANÜ</fullName>
                </value>
                <value>
                    <fullName>Abschlussvollmacht Rahmenvertrag MED ANÜ</fullName>
                </value>
                <value>
                    <fullName>Allgmemeine Vollmacht zu ANÜ Verträgen</fullName>
                </value>
                <value>
                    <fullName>ANÜ Tarifvertrag</fullName>
                </value>
                <value>
                    <fullName>Approbationsurkunde</fullName>
                </value>
                <value>
                    <fullName>Arbeitserlaubnis</fullName>
                </value>
                <value>
                    <fullName>Arbeitsmedizinische Vorsorgebescheinigung (G42 und ggf. G24)</fullName>
                </value>
                <value>
                    <fullName>Arbeitsschutzunterweisung</fullName>
                </value>
                <value>
                    <fullName>Arbeits- und Brandschutzunterweisung</fullName>
                </value>
                <value>
                    <fullName>Arbeitszeugnisse</fullName>
                </value>
                <value>
                    <fullName>Aufenthaltstitel befristet</fullName>
                </value>
                <value>
                    <fullName>Aufenthaltstitel unbefristet</fullName>
                </value>
                <value>
                    <fullName>Berufshaftpflichtversicherung (vollumfänglich für Freiberuflichkeit)</fullName>
                </value>
                <value>
                    <fullName>doctari Dosimeter</fullName>
                </value>
                <value>
                    <fullName>Einsatzbogen</fullName>
                </value>
                <value>
                    <fullName>Einwilligung Abrechnungen online</fullName>
                </value>
                <value>
                    <fullName>Einwilligung Datenweitergabe</fullName>
                </value>
                <value>
                    <fullName>Erstunterweisung</fullName>
                </value>
                <value>
                    <fullName>Examensurkunde</fullName>
                </value>
                <value>
                    <fullName>Facharzturkunde/-n</fullName>
                </value>
                <value>
                    <fullName>Facharzturkunde Zusatzbezeichnung/-en</fullName>
                </value>
                <value>
                    <fullName>Fachkundennachweise</fullName>
                </value>
                <value>
                    <fullName>Fachkundennachweise Strahlenschutz</fullName>
                </value>
                <value>
                    <fullName>Fachweiterbildung</fullName>
                </value>
                <value>
                    <fullName>Fiktionsbescheinigung</fullName>
                </value>
                <value>
                    <fullName>Fortbildungszertifikat</fullName>
                </value>
                <value>
                    <fullName>Fort- und Weiterbildungsnachweis</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Quote.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>CheckHUED__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Check HUED</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>T_QuoteCheck__c</fullName>
        <defaultValue>false</defaultValue>
        <label>[T]_QuoteCheck</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Person_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name der Person, mit der ein Vertrag geschlossen werden soll</inlineHelpText>
        <label>Person Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Doctor, Caregiver</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CommentOperationCheck__c</fullName>
        <label>Comment Operation Check</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

classes/AccountQueryLayer.cls
public with sharing class AccountQueryLayer extends SObjectQueryLayer {
    @TestVisible
    protected override Schema.SObjectType getSObjectType() {
            return Account.sObjectType;
    }

    @AuraEnabled(Cacheable=true)
    public static Account getAccountbyQuoteId(String recordId, List<String> typesString) {
            return [
                SELECT Id, EconomicRegion__c,
                    (SELECT Id, Person_Account__r.Name, Person_Account__c, CheckHUED__c, CommentOperationCheck__c, T_QuoteCheck__c FROM Quotes__r WHERE Id = :recordId),
                    (SELECT Id, TypeOfDocument__c, ValidUntil__c FROM Dokumente__r WHERE TypeOfDocument__c IN :typesString)
                FROM Account 
                WHERE Id IN (SELECT Person_Account__c FROM Quote WHERE Id = :recordId)
            ];
    }
}