objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Legal_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Legal Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Legal Entity)</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>doctari_client__c</fullName>
        <label>doctari client</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Campaign.object
<CustomObject>
    <sharingModel>FullAccess</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email_Body__c</fullName>
        <label>Email Body</label>
        <length>4000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is for the relation between Opp and Campaign.
Robin S. 22.02.2019</description>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Für diese Opportunity kann keine Kampagne erstellt werden</errorMessage>
            <filterItems>
                <field>Opportunity.RecordTypeId</field>
                <operation>equals</operation>
                <value>Substitute Doctor, Substitute Caregiver, Recruitment Doctor, Recruitment Caregiver</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject_Line__c</fullName>
        <description>This is the subject line for the offer mail.
Robin S. 12.04.2019</description>
        <label>Subject Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MarketoAPICallout__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to start the API Callout Trigger</description>
        <label>MarketoAPICallout</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>MarketoID__c</fullName>
        <externalId>true</externalId>
        <label>Marketo ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Dokumente__c.object
<CustomObject>
    <label>Unterlagen</label>
    <nameField>
        <label>Dokumente Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unterlagen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dokumente</relationshipLabel>
        <relationshipName>Dokumente</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ValidUntil__c</fullName>
        <label>Valid Until</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AccountType__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Einrichtung</fullName>
                </value>
                <value>
                    <fullName>Pfleger</fullName>
                </value>
                <value>
                    <fullName>Arzt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TypeOfDocument__c</fullName>
        <label>Type Of Document</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>AccountType__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>A1-Bescheinigung</fullName>
                </value>
                <value>
                    <fullName>Abfrage Vorarbeitgeber</fullName>
                </value>
                <value>
                    <fullName>Abschlussvollmacht Rahmenvertrag Ärzte ANÜ</fullName>
                </value>
                <value>
                    <fullName>Abschlussvollmacht Rahmenvertrag Ärzte ANÜ + MED ANÜ</fullName>
                </value>
                <value>
                    <fullName>Abschlussvollmacht Rahmenvertrag MED ANÜ</fullName>
                </value>
                <value>
                    <fullName>Allgmemeine Vollmacht zu ANÜ Verträgen</fullName>
                </value>
                <value>
                    <fullName>ANÜ Tarifvertrag</fullName>
                </value>
                <value>
                    <fullName>Approbationsurkunde</fullName>
                </value>
                <value>
                    <fullName>Arbeitserlaubnis</fullName>
                </value>
                <value>
                    <fullName>Arbeitsmedizinische Vorsorgebescheinigung (G42 und ggf. G24)</fullName>
                </value>
                <value>
                    <fullName>Arbeitsschutzunterweisung</fullName>
                </value>
                <value>
                    <fullName>Arbeits- und Brandschutzunterweisung</fullName>
                </value>
                <value>
                    <fullName>Arbeitszeugnisse</fullName>
                </value>
                <value>
                    <fullName>Aufenthaltstitel befristet</fullName>
                </value>
                <value>
                    <fullName>Aufenthaltstitel unbefristet</fullName>
                </value>
                <value>
                    <fullName>Berufshaftpflichtversicherung (vollumfänglich für Freiberuflichkeit)</fullName>
                </value>
                <value>
                    <fullName>doctari Dosimeter</fullName>
                </value>
                <value>
                    <fullName>Einsatzbogen</fullName>
                </value>
                <value>
                    <fullName>Einwilligung Abrechnungen online</fullName>
                </value>
                <value>
                    <fullName>Einwilligung Datenweitergabe</fullName>
                </value>
                <value>
                    <fullName>Erstunterweisung</fullName>
                </value>
                <value>
                    <fullName>Examensurkunde</fullName>
                </value>
                <value>
                    <fullName>Facharzturkunde/-n</fullName>
                </value>
                <value>
                    <fullName>Facharzturkunde Zusatzbezeichnung/-en</fullName>
                </value>
                <value>
                    <fullName>Fachkundennachweise</fullName>
                </value>
                <value>
                    <fullName>Fachkundennachweise Strahlenschutz</fullName>
                </value>
                <value>
                    <fullName>Fachweiterbildung</fullName>
                </value>
                <value>
                    <fullName>Fiktionsbescheinigung</fullName>
                </value>
                <value>
                    <fullName>Fortbildungszertifikat</fullName>
                </value>
                <value>
                    <fullName>Fort- und Weiterbildungsnachweis</fullName>
                </value>
                <value>
                    <fullName>MasernATTEST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Email_Body__c</fullName>
        <description>This field is used for the offer mails.
01.04.2019 Robin S.</description>
        <inlineHelpText>Anrede und Grußform werden automatisch erstellt</inlineHelpText>
        <label>Email Body</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Reisekosten__c</fullName>
        <label>Reisekosten</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Reisekosten</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>StationMulti__c</fullName>
        <label>Station</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>StationMulti</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject_Line__c</fullName>
        <description>This is the subject line for the offer mail.
Robin S. 12.04.2019</description>
        <label>Subject Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContactPersonEmployees__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Person Employees</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Contact Person Employees)</relationshipLabel>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContactPersonSpeciality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Person Speciality</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Contact Person Speciality)</relationshipLabel>
        <relationshipName>Opportunities3</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Quote.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Legal_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Rechtsträger</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes (Legal Entity)</relationshipLabel>
        <relationshipName>Quotes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Person_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name der Person, mit der ein Vertrag geschlossen werden soll</inlineHelpText>
        <label>Person Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Doctor, Caregiver</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>doctari_client__c</fullName>
        <description>Is needed for Landwehr.
Robin S. 14.10.2019</description>
        <label>doctari client</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>doctari Fachpflege GmbH</fullName>
                </value>
                <value>
                    <fullName>doctari Pflege ANÜ GmbH</fullName>
                </value>
                <value>
                    <fullName>doctari Ärzte ANÜ GmbH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ContactPersonEmployees__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Ansprechpartner des Kunden für den Bereich Personal</inlineHelpText>
        <label>Contact Person Employees</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Quotes (Contact Person Employees)</relationshipLabel>
        <relationshipName>Quotes1</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Reisekosten__c.object
<CustomObject>
    <label>Reisekosten</label>
    <nameField>
        <label>Reisekosten Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reisekosten</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Traveling Costs</relationshipLabel>
        <relationshipName>Traveling_Costs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Reisekosten</relationshipLabel>
        <relationshipName>Reisekosten</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Reisekosten</relationshipLabel>
        <relationshipName>Reisekosten</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Institution</fullName>
        <active>true</active>
        <label>Institution</label>
    </recordTypes>
</CustomObject>

objects/Reisekosten_Art__c.object
<CustomObject>
    <label>Reisekosten Art</label>
    <nameField>
        <displayFormat>RA-{0000}</displayFormat>
        <label>Reisekosten Art Nummer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reisekosten Arten</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Reisekosten__c</fullName>
        <label>Reisekosten</label>
        <referenceTo>Reisekosten__c</referenceTo>
        <relationshipLabel>Reisekosten Arten</relationshipLabel>
        <relationshipName>Reisekosten_Arten</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

classes/SObjectFactory.cls
/**
 * Created by cristofers on 2019-04-16.
 */

public class SObjectFactory {

    public static Account generateAccount(){

        Account account = new Account(Name = 'TestAccount',
                Type = 'Customer');

        return account;
    }

    public static Opportunity generateOpportunity(Account acc){
        Opportunity opp = new Opportunity(Name = 'TestOpp',
                CloseDate = System.Today(),
                StageName = 'New',
                AccountId = acc.Id);

        return opp;
    }

    public static Contact generateContact(Account acc){
        Contact contact1 = new Contact(LastName = 'TestContact',
                AccountId = acc.Id,
                Salutation = 'Mr.',
                MarketoID__c = '1030327',
                HasOptedOutOfEmail = false);

        return contact1;
    }

    public static Campaign generateCampaign(Opportunity opp){
        Campaign campaign = new Campaign(
                Name = 'TestCampaign',
                MarketoAPICallout__c = false,
                Opportunity__c = opp.Id,
                Subject_Line__c = 'Hello',
                Email_Body__c = 'Sehr geehrte Damen und Herren, ...'
        );

        return campaign;
    }

    public static CampaignMemberStatus generateCampaignMemberStatus(Campaign campaign){
        CampaignMemberStatus cms = new CampaignMemberStatus(
                CampaignId = campaign.Id,
                HasResponded=false,
                Label = 'In Preparation',
                SortOrder = 3, isDefault = true
        );

        return cms;
    }

    public static CampaignMember generateCampaignMember(Contact contact, Campaign campaign){
        CampaignMember campaignMemberContact1 = new CampaignMember(ContactId = contact.Id,
                CampaignId = campaign.Id,
                Status = 'In Preparation');

        return campaignMemberContact1;
    }

    public static Opportunity generateOpportunity2(Account acc, Contact con){
        Opportunity opp = new Opportunity(Name = 'TestOpp',
                CloseDate = System.Today(),
                StageName = 'New',
                ContactPersonSpeciality__c = con.Id,
                ContactPersonEmployees__c = con.Id,
                StationMulti__c = 'GER',
                AccountId = acc.Id);

        return opp;
    }

    public static Account generatePersonAccount(){
        Id rtype = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Caregiver').getRecordTypeId();
        Account paccount = new Account(FirstName = 'Test',
                LastName = 'Testerino',
                RecordTypeId = rtype);

        return paccount;
    }

    public static Account generateInstitutAccount(){
        Id rtype = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Healthcare Institution').getRecordTypeId();
        Account Iaccount = new Account(Name = 'Test',
                RecordTypeId = rtype);

        return Iaccount;
    }


    public static Quote generateQuote(Account account,Account account2, Opportunity opp){
        Quote quote = new Quote(
                Name = 'Quote',
                OpportunityId = opp.Id,
                Person_Account__c = account.Id,
                Legal_Entity__c = account2.Id,
                doctari_client__c = 'doctari Fachpflege GmbH');
        return quote;
    }

    public static Reisekosten__c generateReisekosten(Account account, Opportunity opp, Quote quote){
        Id rtype = Schema.SObjectType.Reisekosten__c.getRecordTypeInfosByName().get('Doctor/Caregiver').getRecordTypeId();
        Reisekosten__c reisekosten = new Reisekosten__c(
                Name = 'Reisekosten',
                RecordTypeId = rtype,
                Account__c = account.Id,
                Opportunity__c = opp.Id,
                Quote__c = quote.Id);
        return reisekosten;

    }

    public static Reisekosten_Art__c generateReisekostenArt(Reisekosten__c reisekosten){
        Reisekosten_Art__c reisekostenArt = new Reisekosten_Art__c(
                Reisekosten__c = reisekosten.Id);
        return reisekostenArt;

    }

    public static Dokumente__c generateDocument(Account account){
        Id dRtype = Schema.SObjectType.Dokumente__c.getRecordTypeInfosByName().get('Caregiver Document').getRecordTypeId();
        Dokumente__c document = new Dokumente__c(
                Name = 'Dokument',
                RecordTypeId = dRtype,
                AccountType__c = 'Pfleger',
                TypeOfDocument__c = 'MasernATTEST',
                Account__c = account.Id,
                ValidUntil__c = Date.today().addDays(10));
        return document;

    }



}