objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>doctari_client__c</fullName>
        <label>doctari client</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Quote.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Person_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name der Person, mit der ein Vertrag geschlossen werden soll</inlineHelpText>
        <label>Person Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Doctor, Caregiver</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>doctari_client__c</fullName>
        <description>Is needed for Landwehr.
Robin S. 14.10.2019</description>
        <label>doctari client</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>doctari Fachpflege GmbH</fullName>
                </value>
                <value>
                    <fullName>doctari Pflege ANÜ GmbH</fullName>
                </value>
                <value>
                    <fullName>doctari Ärzte ANÜ GmbH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/QuoteCloneControllerTest.cls
@IsTest
private class QuoteCloneControllerTest {
    @testSetup
    static void setup() {
        Account acc = SObjectFactory.generateAccount();
        INSERT acc;
        
        Account pers = new Account();
        pers.FirstName = 'Max';
        pers.LastName = 'Mustermann';
        INSERT pers;
        
		Opportunity opp = SObjectFactory.generateOpportunity(acc);
        INSERT opp;
        
        Quote quote = new Quote();
        quote.OpportunityId = opp.ID;
        quote.Person_Account__c = pers.Id;
        quote.Name = 'UnitTest';
        quote.doctari_client__c = 'doctari Fachpflege GmbH';
        INSERT quote;
    }
    
	@isTest static void cloneQuote() {
		List<Quote> quoteList = [Select id, OpportunityId From Quote Where Name = 'UnitTest'];
        List<List<Quote>> invocableParams = new List<List<Quote>> {quoteList};
            
        Test.startTest();
        QuoteCloneController.cloneQuote(invocableParams);
        Test.stopTest();
        
        List<Quote> foundQuotes = [Select id, OpportunityId From Quote Where Name = 'UnitTest'];
        system.assertEquals(2, foundQuotes.size());
    }
}