objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Neu</fullName>
                    <default>true</default>
                    <label>Neu</label>
                </value>
                <value>
                    <fullName>Qualifizierung</fullName>
                </value>
                <value>
                    <fullName>Aktiv</fullName>
                </value>
                <value>
                    <fullName>Aktiv_Mailing</fullName>
                    <label>Aktiv - Mailing</label>
                </value>
                <value>
                    <fullName>Aktiv - Vermittelbar</fullName>
                </value>
                <value>
                    <fullName>Inaktiv</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Campaign.object
<CustomObject>
    <sharingModel>FullAccess</sharingModel>
    <fields>
        <fullName>Email_Body__c</fullName>
        <label>Email Body</label>
        <length>4000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Campaign_ID__c</fullName>
        <description>Autonumber for the Campaign. Is used for the better identification of a campaign.
Robin S. 08.04.2019</description>
        <displayFormat>KD{000000}</displayFormat>
        <label>Campaign ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is for the relation between Opp and Campaign.
Robin S. 22.02.2019</description>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Für diese Opportunity kann keine Kampagne erstellt werden</errorMessage>
            <filterItems>
                <field>Opportunity.RecordTypeId</field>
                <operation>equals</operation>
                <value>Substitute Doctor, Substitute Caregiver, Recruitment Doctor, Recruitment Caregiver</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject_Line__c</fullName>
        <description>This is the subject line for the offer mail.
Robin S. 12.04.2019</description>
        <label>Subject Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>T_Sender_Name__c</fullName>
        <formula>IF( Opportunity__r.RecordType.DeveloperName = &quot;SubstituteCaregiver&quot;, &quot;doctari - Pflege Jobs&quot;, &quot;doctari - Aerzte Jobs&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>[T] Sender Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Jobportal_Link__c</fullName>
        <formula>IF(  PrivateCampaign__c,&quot;Der Job ist nicht veröffentlicht&quot;,IF( CONTAINS(Opportunity__r.RecordType.DeveloperName, &quot;Caregiver&quot;), &quot;https://mein.doctari.de/jobs/&quot; &amp; Campaign_ID__c , &quot;https://mein.doctari.de/jobs/&quot; &amp; Campaign_ID__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Jobportal Link</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>T_Sender_Address__c</fullName>
        <description>This sender address is used for the offer Mailing via Marketo. 
Robin S. 19.07.2019</description>
        <formula>IF( Opportunity__r.RecordType.DeveloperName = &quot;SubstituteCaregiver&quot;, &quot;pflege@mail.doctari.de&quot;, &quot;aerzte@mail.doctari.de&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>[T] Sender Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MarketoAPICallout__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to start the API Callout Trigger</description>
        <label>MarketoAPICallout</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Titel__c</fullName>
        <label>Titel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Titel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>aktiv</fullName>
                    <default>true</default>
                    <label>aktiv</label>
                </value>
                <value>
                    <fullName>inaktiv</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MarketoID__c</fullName>
        <externalId>true</externalId>
        <label>Marketo ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/CampaignMembersQueryLayer.cls
/**
 * Created by Cristofer Soler - 2019-04-01.
 */

public with sharing class CampaignMembersQueryLayer extends SObjectQueryLayer {
        @TestVisible
        protected override Schema.SObjectType getSObjectType() {
                return CampaignMember.sObjectType;
        }
        //for MC
        public List<CampaignMember> getCMBasedOnCampaignIdSetAndStatus(Set<Id> campaignIds) {
                return [
                        SELECT Id, CampaignId, Status, ContactId, Contact.HasOptedOutOfEmail, Contact.Email, Contact.FirstName, Contact.LastName, Contact.Titel__c, Contact.Salutation, Campaign.Campaign_ID__c, Campaign.Status, Campaign.Opportunity__c, Campaign.Subject_Line__c , Campaign.Email_Body__c, Campaign.Jobportal_Link__c, Campaign.T_Sender_Address__c, Campaign.T_Sender_Name__c
                        FROM CampaignMember
                        WHERE CampaignId IN :campaignIds
                        AND (Status = 'In Preparation' OR Status = 'Cancelled')
                        AND Contact.HasOptedOutOfEmail = false
                        AND Contact.Account.Status__c != 'Inaktiv'
                        ];
            }
    
        //Marketo
        public List<CampaignMember> getCMBasedOnCampaignIdAndStatus(Id campaignId) {
                return [
                        SELECT Id, CampaignId, Status, ContactId, Contact.HasOptedOutOfEmail, Contact.MarketoID__c, Contact.Email, Contact.FirstName, Contact.LastName, Contact.Titel__c, Contact.Salutation, Campaign.Campaign_ID__c, Campaign.Status, Campaign.MarketoAPICallout__c, Campaign.Opportunity__c, Campaign.Subject_Line__c , Campaign.Email_Body__c, Campaign.Jobportal_Link__c, Campaign.T_Sender_Address__c
                        FROM CampaignMember
                        WHERE CampaignId = :campaignId
                        AND Campaign.MarketoAPICallout__c = true
                        AND (Status = 'In Preparation' OR Status = 'Cancelled')
                        AND Contact.HasOptedOutOfEmail = false
                        AND Contact.MarketoID__c != null
                ];
        }
        //MC
        public List<CampaignMember> getCMBasedOnCampaignIdAndStatusMC(Id campaignId) {
            return [
                    SELECT Id, CampaignId, Status, ContactId, Contact.HasOptedOutOfEmail, Contact.Email, Contact.FirstName, Contact.LastName, Contact.Titel__c, Contact.Salutation, Campaign.Campaign_ID__c, Campaign.Status, Campaign.Opportunity__c, Campaign.Subject_Line__c , Campaign.Email_Body__c, Campaign.Jobportal_Link__c, Campaign.T_Sender_Address__c, Campaign.T_Sender_Name__c
                    FROM CampaignMember
                    WHERE CampaignId = :campaignId
                    AND (Status = 'In Preparation' OR Status = 'Cancelled')
                    AND Contact.HasOptedOutOfEmail = false
                    AND Contact.Account.Status__c != 'Inaktiv'
            ];
        }
        //for Marketo
        public List<CampaignMember> getCMBasedOnCampaignIdAndOptOutTrue(Id campaignId) {
            return [
                    SELECT Id, Status, CampaignId, Contact.HasOptedOutOfEmail
                    FROM CampaignMember
                    WHERE CampaignId = :campaignId
                    AND Contact.HasOptedOutOfEmail = true
            ];
        }
        //for MC
        public List<CampaignMember> getCMBasedOnCampaignIdSetAndOptOutTrue(Set<Id> campaignIds) {
            return [
                    SELECT Id, Status, CampaignId, Contact.HasOptedOutOfEmail, Contact.Status__c
                    FROM CampaignMember
                    WHERE CampaignId IN :campaignIds
                    AND (Contact.HasOptedOutOfEmail = true OR Contact.Account.Status__c = 'Inaktiv')
            ];
        }
    
        public List<CampaignMember> getCMBasedOnCampaignCheckMarketoId(Id campaignId) {
            return [
                    SELECT Id, CampaignId, Status, ContactId, Contact.HasOptedOutOfEmail, Contact.MarketoID__c, Campaign.Status, Campaign.Campaign_ID__c, Campaign.MarketoAPICallout__c, Campaign.Opportunity__c, Campaign.Subject_Line__c ,Campaign.Email_Body__c, Campaign.T_Sender_Address__c, Campaign.Jobportal_Link__c, Campaign.T_Sender_Name__c
                    FROM CampaignMember
                    WHERE CampaignId = :campaignId
                    AND (Status = 'In Preparation' OR Status = 'Cancelled')
            ];
        }
        //for Marketo
        public List<CampaignMember> getCMBasedOnCampaignWithStatusSend(Id campaignId) {
            return [
                    SELECT Id, CampaignId, Status, ContactId, Contact.HasOptedOutOfEmail, Contact.MarketoID__c, Campaign.Status, Campaign.Campaign_ID__c, Campaign.MarketoAPICallout__c, Campaign.Opportunity__c, Campaign.Subject_Line__c ,Campaign.Email_Body__c, Campaign.T_Sender_Address__c, Campaign.Jobportal_Link__c
                    FROM CampaignMember
                    WHERE CampaignId = :campaignId
                    AND Campaign.MarketoAPICallout__c = true
                    AND (Status = 'Sent')
                    AND Contact.HasOptedOutOfEmail = false
                    AND Contact.MarketoID__c != null
            ];
        }
        //for MC
        public List<CampaignMember> getCMBasedOnCampaignWithStatusSendMC(Id campaignId) {
            return [
                    SELECT Id, CampaignId, Status, ContactId, Contact.HasOptedOutOfEmail, Campaign.Status, Campaign.Campaign_ID__c,  Campaign.Opportunity__c, Campaign.Subject_Line__c ,Campaign.Email_Body__c, Campaign.T_Sender_Address__c, Campaign.Jobportal_Link__c
                    FROM CampaignMember
                    WHERE CampaignId = :campaignId
                    AND (Status = 'Sent')
                    AND Contact.HasOptedOutOfEmail = false
            ];
        }
    
        //for MC
        public List<CampaignMember> getCMBasedOnCampaignSetWithStatusSend(Set<Id> campaignIds) {
            return [
                    SELECT Id, CampaignId, Status, ContactId, Contact.HasOptedOutOfEmail, Contact.MarketoID__c, Campaign.Status, Campaign.Opportunity__c, Campaign.Subject_Line__c ,Campaign.Email_Body__c
                    FROM CampaignMember
                    WHERE CampaignId IN :campaignIds
                    AND Status = 'Sent'
                    AND Contact.HasOptedOutOfEmail = false
            ];
        }
    
    
    
    }