objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>InstitutionType__c</fullName>
        <label>Institution Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Akutklinik</fullName>
                </value>
                <value>
                    <fullName>alle</fullName>
                </value>
                <value>
                    <fullName>Ambulanter Pflegedienst</fullName>
                </value>
                <value>
                    <fullName>Ambulanz</fullName>
                </value>
                <value>
                    <fullName>Einzelpraxis</fullName>
                </value>
                <value>
                    <fullName>Gemeinschaftspraxis</fullName>
                </value>
                <value>
                    <fullName>Haus der Grund- und Regelversorgung</fullName>
                </value>
                <value>
                    <fullName>Haus der Maximalversorgung</fullName>
                </value>
                <value>
                    <fullName>Medizinisches Versorgungszentrum</fullName>
                </value>
                <value>
                    <fullName>Pflegeheim</fullName>
                </value>
                <value>
                    <fullName>Rehaklinik</fullName>
                </value>
                <value>
                    <fullName>Rehaklinik mit Akutbereich</fullName>
                </value>
                <value>
                    <fullName>Rettungsdienst</fullName>
                </value>
                <value>
                    <fullName>Schwerpunktkrankenhaus</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TechnicalQualifications__c</fullName>
        <label>Technical Qualifications</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Fachkunde</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

objects/CompetenceCaregiverAccount__c.object
<CustomObject>
    <label>Kompetenz Pflege Account</label>
    <nameField>
        <label>Kompetenz Pfleger Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kompetenzen Pflege Account</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>CaregiverFurtherEducation__c</fullName>
        <label>Caregiver Further Education</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pflege_Weiterbildungen</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

objects/CompetenceDoctorAccount__c.object
<CustomObject>
    <label>Kompetenz Arzt Account</label>
    <nameField>
        <label>Competence Docotor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kompetenz Arzt Account</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>MedicalDiscipline__c</fullName>
        <label>Medical Discipline</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Fachbereich</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>QualificationLevel__c</fullName>
        <label>Qualification Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assistenzarzt</fullName>
                </value>
                <value>
                    <fullName>Facharzt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AdditionalDesignations__c</fullName>
        <label>Additional Designations</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Zusatzbezeichnung</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

objects/Contract.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Station__c</fullName>
        <inlineHelpText>beschreibt die Station, auf der der Einsatz erfolgen soll</inlineHelpText>
        <label>Station</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>DateTo__c</fullName>
        <label>Date to Ⓜ️</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Keyword__c</fullName>
        <description>https://doctari.atlassian.net/browse/SFC-3050
Die User sollen auf der Opportunity die Möglichkeit bekommen, in einem Feld Stichworte für die Volltextsuche zu hinterlegen. (Feldname: Stichwortsuche CV)</description>
        <inlineHelpText>Die in Textkernel hinterlegten Lebensläufe können nach Schlagworten durchsucht werden.Trenne die Schlagworte mit einem Semikolon</inlineHelpText>
        <label>Keyword search CV</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Station__c</fullName>
        <label>Station Ⓜ️</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ITS</fullName>
                </value>
                <value>
                    <fullName>ANÄ</fullName>
                </value>
                <value>
                    <fullName>NS</fullName>
                </value>
                <value>
                    <fullName>Ki-ITS</fullName>
                </value>
                <value>
                    <fullName>ZNA</fullName>
                </value>
                <value>
                    <fullName>IMC</fullName>
                </value>
                <value>
                    <fullName>OP</fullName>
                </value>
                <value>
                    <fullName>MTRA</fullName>
                </value>
                <value>
                    <fullName>Reha</fullName>
                </value>
                <value>
                    <fullName>GP</fullName>
                </value>
                <value>
                    <fullName>Amb PD</fullName>
                </value>
                <value>
                    <fullName>PfHeim</fullName>
                </value>
                <value>
                    <fullName>GYN</fullName>
                </value>
                <value>
                    <fullName>GER</fullName>
                </value>
                <value>
                    <fullName>CHI</fullName>
                </value>
                <value>
                    <fullName>HNO</fullName>
                </value>
                <value>
                    <fullName>INN</fullName>
                </value>
                <value>
                    <fullName>NEU</fullName>
                </value>
                <value>
                    <fullName>ORT</fullName>
                </value>
                <value>
                    <fullName>PSY</fullName>
                </value>
                <value>
                    <fullName>PNE</fullName>
                </value>
                <value>
                    <fullName>URO</fullName>
                </value>
                <value>
                    <fullName>KAR</fullName>
                </value>
                <value>
                    <fullName>GSO</fullName>
                </value>
                <value>
                    <fullName>ANG</fullName>
                </value>
                <value>
                    <fullName>KRS</fullName>
                </value>
                <value>
                    <fullName>DIA</fullName>
                </value>
                <value>
                    <fullName>NEO</fullName>
                </value>
                <value>
                    <fullName>HYG</fullName>
                </value>
                <value>
                    <fullName>WEA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DateFrom__c</fullName>
        <label>Date From Ⓜ️</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PlacementModel__c</fullName>
        <label>Placement Model Ⓜ️</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Vermittlungsmodell</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>InstitutionType__c</fullName>
        <formula>TEXT( Account.HealthcareInstitutionType__c )</formula>
        <label>Institution Type Ⓜ️</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TechnicalQualifications__c</fullName>
        <label>Technical Qualifications</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Fachkunde</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

objects/QualificationCaregiver__c.object
<CustomObject>
    <label>Qualifikation Pfleger</label>
    <nameField>
        <label>Qualification Caregiver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Qualifikationen Pfleger</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>CaregiverJobs__c</fullName>
        <label>Ⓜ️ Caregiver Jobs</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pflege_Berufe</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

objects/QualificationDoctor__c.object
<CustomObject>
    <label>Qualifikation Arzt</label>
    <nameField>
        <label>Competence Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Qualifikationen Arzt</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Dies ist nur für &apos;Vertretung Arzt&apos; möglich</errorMessage>
            <filterItems>
                <field>Opportunity.RecordTypeId</field>
                <operation>equals</operation>
                <value>Substitute Doctor, Recruitment Doctor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Qualification Doctor</relationshipLabel>
        <relationshipName>Qualifications_Doctor</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MedicalDiscipline__c</fullName>
        <description>NEW Field for speciality
Because the old field don&apos;t use the global value set.
Robin S. 20.06.2019</description>
        <label>Ⓜ️ Medical Discipline</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Fachbereich</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>QualificationLevel__c</fullName>
        <label>Ⓜ️ Qualification Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assistenzarzt</fullName>
                </value>
                <value>
                    <fullName>Facharzt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AdditionalDesignations__c</fullName>
        <label>Additional Designations</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Zusatzbezeichnung</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TechnicalQualifications__c</fullName>
        <label>Technical Qualifications</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Fachkunde</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

objects/SearchPreset__mdt.object
<CustomObject>
    <description>Search Presets for doctor and care givers</description>
    <label>Search Preset</label>
    <pluralLabel>Search Preset</pluralLabel>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Doctor</fullName>
                    <default>true</default>
                    <label>Doctor</label>
                </value>
                <value>
                    <fullName>Caregiver</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MedicalDiscipline__c</fullName>
        <label>Medical Discipline</label>
        <length>1024</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>AdditionalDesignations__c</fullName>
        <label>Additional Designations</label>
        <length>1024</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

classes/TKQueryLayer.cls
/**
 * Created by khanhhua on 2020-08-17.
 */
public with sharing class TKQueryLayer {
    @AuraEnabled(Cacheable=true)
    public static Opportunity getOpportunityByCampaignId(String recordId) {
        return [
            SELECT Id, RecordType.DeveloperName, PlacementModel__c, StageName, InstitutionType__c, DateFrom__c, DateTo__c, Station__c,
                Keyword__c, Account.Id, Account.ShippingAddress, Account.ShippingLatitude, Account.ShippingLongitude,
                (SELECT Id, MedicalDiscipline__c, QualificationLevel__c, TechnicalQualifications__c, AdditionalDesignations__c
                    FROM Qualifications_Doctor__r),
                (SELECT Id, CaregiverJobs__c, CaregiverFurtherEducation__c, CaregiverPracticalExperience__c
                FROM Qualifications_Caregiver__r)
            FROM Opportunity
            WHERE Id IN (SELECT Opportunity__c FROM Campaign WHERE Id =: recordId)
        ];
    }

    @AuraEnabled(cacheable=true)
    public static Account getCandidateById(String recordId) {
        return [
            SELECT Id, RecordType.DeveloperName, TechnicalQualifications__c, PlacementTypes__c, PersonMailingAddress, PersonMailingLatitude, PersonMailingLongitude, RadiusKm__c,
                   (SELECT MedicalDiscipline__c, AdditionalDesignations__c, QualificationLevel__c
                   FROM Kompetenzen__r),
                   (SELECT CaregiverJob__c, CaregiverFurtherEducation__c, CaregiverPracticalExperience__c
                   FROM KompetenzenPflegerAccount__r),
                   (SELECT AccountId, Id, OwnerId, Person_Account__c, OperatingTime__c 
                   FROM Contracts__r 
                   WHERE Person_Account__c =: recordId)
            FROM Account
            WHERE Id =: recordId
        ];
    }

    @AuraEnabled(cacheable=true)
    public static List<SearchPreset__mdt> getSearchPresets() {
        return [
            SELECT Label, DeveloperName, Operator__c, AdditionalDesignations__c, MedicalDiscipline__c, Type__c, CaregiverJob__c, OtherTrainingAndDevelopment__c, 
            CaregiverFurtherEducation__c, CaregiverPracticalExperience__c
            FROM SearchPreset__mdt
        ];
    }
}