objects/Auspraegung__c.object
<CustomObject>
    <label>Reisekosten Ausprägung</label>
    <nameField>
        <displayFormat>AA-{0000}</displayFormat>
        <label>Ausprägung Nummer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reisekosten Ausprägungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Zuschlag__c</fullName>
        <defaultValue>10</defaultValue>
        <label>Zuschlag</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Reisekosten_Art__c</fullName>
        <label>Reisekosten Art</label>
        <referenceTo>Reisekosten_Art__c</referenceTo>
        <relationshipName>Auspraegungen</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Anzahl_Sonstiges__c</fullName>
        <label>Anzahl Sonstiges</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Anzahl_Flug_Tickets__c</fullName>
        <label>Anzahl Flug-Tickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Zuschlag_arbeitstaeglich__c</fullName>
        <label>Zuschlag arbeitstäglich</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>PNV_Heimfahrten_pro_Monat__c</fullName>
        <label>ÖPNV Heimfahrten pro Monat</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Zuschlag_kalendertaeglich__c</fullName>
        <label>Zuschlag kalendertäglich</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Bahn_Heimfahrten_pro_Monat__c</fullName>
        <label>Bahn Heimfahrten pro Monat</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>maximaler_Betrag_Sonstiges__c</fullName>
        <label>maximaler Betrag Sonstiges</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>maximaler_Betrag_Flugticket__c</fullName>
        <label>maximaler Betrag Flugticket</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Auspraegung_Unterkunft_Klinik__c</fullName>
        <label>Ausprägung Unterkunft Klinik</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>kalendertäglich</fullName>
                </value>
                <value>
                    <fullName>arbeitstäglich</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>krankheitsbedingte_Auspraegung__c</fullName>
        <label>krankheitsbedingte Ausprägung</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fruehstueck_bis_maximaler_Betrag__c</fullName>
        <label>Frühstück bis maximaler Betrag</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>maximaler_Betrag_arbeitstaeglich__c</fullName>
        <label>maximaler Betrag arbeitstäglich</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>maximaler_Betrag_kalendert_glich__c</fullName>
        <label>maximaler Betrag kalendertäglich</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Auspraegung_Fahrkosten_Mobilitaet__c</fullName>
        <label>Ausprägung Fahrkosten und Mobilität</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>wöchentlich</fullName>
                </value>
                <value>
                    <fullName>arbeitstäglich</fullName>
                </value>
                <value>
                    <fullName>An- und Abfahrt pro Monat</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Auspraegung_Mitarbeiter_Unterkunft__c</fullName>
        <label>Ausprägung Mitarbeiter Unterkunft</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Übernachtung</fullName>
                </value>
                <value>
                    <fullName>Frühstück</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>KM_Pauschale_Heimfahrten_pro_Monat__c</fullName>
        <label>KM-Pauschale Heimfahrten pro Monat</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Uebernachtung_bis_maximaler_Betrag__c</fullName>
        <label>Übernachtung bis maximaler Betrag</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>maximaler_Betrag_Reisekostenrechts__c</fullName>
        <label>maximaler Betrag (Reisekostenrechts)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Einmalpauschale_bis_maximaler_Betrag__c</fullName>
        <label>Einmalpauschale bis maximaler Betrag</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>maximaler_Betrag_krankheitsb_Ausfall__c</fullName>
        <label>maximaler Betrag krankheitsb. Ausfall</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Auspraegung_Fahrkosten_und_Mobilitaet_B__c</fullName>
        <label>Ausprägung Fahrkosten und Mobilität Bahn</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>An- und Abreise Auftrag</fullName>
                </value>
                <value>
                    <fullName>arbeitstäglich</fullName>
                </value>
                <value>
                    <fullName>Heimfahrten pro Monat</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Auspraegung_Fahrkosten_und_Mobilitaet_O__c</fullName>
        <label>Ausprägung Fahrkosten und Mobilität ÖPNV</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>An- und Abreise Auftrag</fullName>
                </value>
                <value>
                    <fullName>arbeitstäglich</fullName>
                </value>
                <value>
                    <fullName>Heimfahrten pro Monat</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Reisekosten__c.object
<CustomObject>
    <label>Reisekosten</label>
    <nameField>
        <label>Reisekosten Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reisekosten</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Traveling Costs</relationshipLabel>
        <relationshipName>Traveling_Costs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Refund__c</fullName>
        <label>Refund</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Nein</fullName>
                </value>
                <value>
                    <fullName>Ja</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Reisekosten</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Traveling Costs</relationshipLabel>
        <relationshipName>Traveling_Costs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Accommodation_Refund__c</fullName>
        <label>Accommodation Refund</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Nein</fullName>
                </value>
                <value>
                    <fullName>Ja</fullName>
                </value>
                <value>
                    <fullName>Buchung über Doctari</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Reisekosten_Art__c.object
<CustomObject>
    <label>Reisekosten Art</label>
    <nameField>
        <displayFormat>RA-{0000}</displayFormat>
        <label>Reisekosten Art Nummer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reisekosten Arten</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Sonstiges__c</fullName>
        <label>Sonstiges</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reisekosten__c</fullName>
        <label>Reisekosten</label>
        <referenceTo>Reisekosten__c</referenceTo>
        <relationshipLabel>Reisekosten Arten</relationshipLabel>
        <relationshipName>Reisekosten_Arten</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>for_Month_Quote__c</fullName>
        <description>SFC-2293</description>
        <label>for Month/Quote</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>pro Monat</fullName>
                </value>
                <value>
                    <fullName>pro Einsatz</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Verpflegung_Erstattung__c</fullName>
        <label>Verpflegung Erstattung</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Verpflegungsmehraufwendungen nach den Regelungen des Reisekostenrechts</fullName>
                </value>
                <value>
                    <fullName>Einmalpauschale (steuerpflichtig)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unterkunft_Erstattung_Art_Klinik__c</fullName>
        <label>Unterkunft Erstattung Art Klinik</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Einmalpauschale</fullName>
                </value>
                <value>
                    <fullName>per Unterkunftsrechnung</fullName>
                </value>
                <value>
                    <fullName>arbeitstäglich inkl. An- und Abreise</fullName>
                </value>
                <value>
                    <fullName>kalendertäglich</fullName>
                </value>
                <value>
                    <fullName>bei krankheitsbedingten Ausfall</fullName>
                    <isActive>false</isActive>
                    <label>bei krankheitsbedingten Ausfall</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unterkunft_Erstattung_Art_Mitarbeiter__c</fullName>
        <label>Unterkunft Erstattung Art Mitarbeiter</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Einmalpauschale (steuerpflichtig)</fullName>
                </value>
                <value>
                    <fullName>per Unterkunftsrechnung</fullName>
                </value>
                <value>
                    <fullName>pro Übernachtung</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fahrkosten_und_Mobilit_t_Erstattungsart__c</fullName>
        <label>Fahrkosten und Mobilität Erstattungsart</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>km-Pauschale mit dem privaten PkW nach den Regelungen des Reisekostenrechts</fullName>
                </value>
                <value>
                    <fullName>Bahntickets</fullName>
                </value>
                <value>
                    <fullName>ÖPNV - Tickets</fullName>
                </value>
                <value>
                    <fullName>Taxifahrten</fullName>
                </value>
                <value>
                    <fullName>Flug - Tickets</fullName>
                </value>
                <value>
                    <fullName>Mietfahrzeug</fullName>
                </value>
                <value>
                    <fullName>Bahncard</fullName>
                </value>
                <value>
                    <fullName>Fahrradverleih</fullName>
                </value>
                <value>
                    <fullName>Maut</fullName>
                </value>
                <value>
                    <fullName>Sonstiges</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/ReisekostenArtQueryLayer.cls
public with sharing class ReisekostenArtQueryLayer extends SObjectQueryLayer {
    @TestVisible
    protected override Schema.SObjectType getSObjectType() {
            return Reisekosten_Art__c.sObjectType;
    }

    
    @AuraEnabled(Cacheable=true)
    public static List<Reisekosten_Art__c> getReisekostenArtenFromRK(String recordId, String recordTypeName, String categoryName) {
            return [
                    SELECT Id, Reisekosten__c, Reisekosten__r.RecordType.Name,Reisekosten__r.Category__c, Reisekosten__r.Contract__c, Reisekosten__r.Quote__c, Reisekosten__r.Accommodation_Refund__c, Reisekosten__r.Refund__c, Fahrkosten_und_Mobilit_t_Erstattungsart__c, Sonstiges__c, for_Month_Quote__c, Unterkunft_Erstattung_Art_Klinik__c, Unterkunft_Erstattung_Art_Mitarbeiter__c, Verpflegung_Erstattung__c, 
                	(Select id, Auspraegung_Mitarbeiter_Unterkunft__c,Auspraegung_Fahrkosten_Mobilitaet__c,Anzahl_Sonstiges__c,Auspraegung_Fahrkosten_und_Mobilitaet_B__c,Auspraegung_Fahrkosten_und_Mobilitaet_O__c,Auspraegung_Unterkunft_Klinik__c, Bahn_Heimfahrten_pro_Monat__c, KM_Pauschale_Heimfahrten_pro_Monat__c, krankheitsbedingte_Auspraegung__c, maximaler_Betrag_arbeitstaeglich__c,maximaler_Betrag_Flugticket__c,maximaler_Betrag_kalendert_glich__c, maximaler_Betrag_krankheitsb_Ausfall__c, maximaler_Betrag_Sonstiges__c, Zuschlag__c,Zuschlag_arbeitstaeglich__c, Zuschlag_kalendertaeglich__c, PNV_Heimfahrten_pro_Monat__c, Fruehstueck_bis_maximaler_Betrag__c, Uebernachtung_bis_maximaler_Betrag__c, maximaler_Betrag_Reisekostenrechts__c, Einmalpauschale_bis_maximaler_Betrag__c, Anzahl_Flug_Tickets__c FROM Auspraegungen__r)
                    FROM Reisekosten_Art__c
                   WHERE (Reisekosten__r.Quote__c = :recordId OR Reisekosten__r.Contract__c = :recordId) AND Reisekosten__r.RecordType.Name = :recordTypeName AND Reisekosten__r.Category__c = :categoryName
            ];
            
    }
    

}