objects/Campaign.object
<CustomObject>
    <sharingModel>FullAccess</sharingModel>
    <fields>
        <fullName>Email_Body__c</fullName>
        <label>Email Body</label>
        <length>4000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Campaign_ID__c</fullName>
        <description>Autonumber for the Campaign. Is used for the better identification of a campaign.
Robin S. 08.04.2019</description>
        <displayFormat>KD{000000}</displayFormat>
        <label>Campaign ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is for the relation between Opp and Campaign.
Robin S. 22.02.2019</description>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Für diese Opportunity kann keine Kampagne erstellt werden</errorMessage>
            <filterItems>
                <field>Opportunity.RecordTypeId</field>
                <operation>equals</operation>
                <value>Substitute Doctor, Substitute Caregiver, Recruitment Doctor, Recruitment Caregiver</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject_Line__c</fullName>
        <description>This is the subject line for the offer mail.
Robin S. 12.04.2019</description>
        <label>Subject Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Jobportal_Link__c</fullName>
        <formula>IF(  PrivateCampaign__c,&quot;Der Job ist nicht veröffentlicht&quot;,IF( CONTAINS(Opportunity__r.RecordType.DeveloperName, &quot;Caregiver&quot;), &quot;https://mein.doctari.de/jobs/&quot; &amp; Campaign_ID__c , &quot;https://mein.doctari.de/jobs/&quot; &amp; Campaign_ID__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Jobportal Link</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MarketoAPICallout__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to start the API Callout Trigger</description>
        <label>MarketoAPICallout</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>T_MarketoSenderAddress__c</fullName>
        <formula>IF( Opportunity__r.RecordType.DeveloperName = &quot;SubstituteCaregiver&quot;, &quot;pflege@doctari.de&quot;, &quot;aerzte@doctari.de&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>[T]_MarketoSenderAddress</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MarketoID__c</fullName>
        <externalId>true</externalId>
        <label>Marketo ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Debug__c.object
<CustomObject>
    <description>This object lists all exception errors for Apex Error Exceptions.</description>
    <label>Debug</label>
    <nameField>
        <displayFormat>DB-{00000}</displayFormat>
        <label>Debug Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debugs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Message__c</fullName>
        <description>The error message in case there was an exception.</description>
        <label>Message</label>
        <length>130000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MarketoErrorNumber__c</fullName>
        <description>Marketo error Number for the thrown Apex Callout.</description>
        <label>MarketoErrorNumber</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Email_Body__c</fullName>
        <description>This field is used for the offer mails.
01.04.2019 Robin S.</description>
        <inlineHelpText>Anrede und Grußform werden automatisch erstellt</inlineHelpText>
        <label>Email Body</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Subject_Line__c</fullName>
        <description>This is the subject line for the offer mail.
Robin S. 12.04.2019</description>
        <label>Subject Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>doctari</fullName>
                </value>
                <value>
                    <fullName>doctari Ärzte Plus</fullName>
                </value>
                <value>
                    <fullName>doctari Ärzte ANÜ</fullName>
                </value>
                <value>
                    <fullName>doctari Pflege</fullName>
                </value>
                <value>
                    <fullName>doctari Fachpflege</fullName>
                </value>
                <value>
                    <fullName>doctari Pflege ANÜ</fullName>
                </value>
                <value>
                    <fullName>doctari Med ANÜ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Register__c</fullName>
        <description>This field is used for the offer Mailing via Marketo. 
Robin S. 11.04.2019</description>
        <formula>IF(City=&quot;Hamburg&quot;, &quot;Amtsgericht Hamburg, HRB 123378 Sitz der Gesellschaft: Hamburg&quot;, &quot;Amtsgericht Berlin (Charlottenburg), HRB 146498 Sitz der Gesellschaft: Berlin&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Register</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeatOfTheSociety__c</fullName>
        <formula>IF(ISPICKVAL(Company__c, &apos;doctari&apos;) || ISPICKVAL(Company__c, &apos;doctari Ärzte Plus&apos;) || ISPICKVAL(Company__c, &apos;doctari Ärzte ANÜ&apos;) || ISPICKVAL(Company__c, &apos;doctari Med ANÜ&apos;), &apos;Berlin&apos;, 
IF(ISPICKVAL(Company__c, &apos;doctari Pflege&apos;) || ISPICKVAL(Company__c, &apos;doctari Fachpflege&apos;) || ISPICKVAL(Company__c, &apos;doctari Pflege ANÜ&apos;), &apos;Hamburg&apos;, 
&apos;&apos; 
))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Seat of the Society</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CommercialRegister__c</fullName>
        <formula>IF(ISPICKVAL(Company__c, &apos;doctari&apos;), &apos;HRB 146498&apos;,
IF(ISPICKVAL(Company__c, &apos;doctari Ärzte Plus&apos;), &apos;HRB 181928&apos;,
IF(ISPICKVAL(Company__c, &apos;doctari Ärzte ANÜ&apos;), &apos;HRB 152700&apos;,
IF(ISPICKVAL(Company__c, &apos;doctari Med ANÜ&apos;), &apos;HRB 181928&apos;,
IF(ISPICKVAL(Company__c, &apos;doctari Pflege&apos;), &apos;HRB 123378&apos;,
IF(ISPICKVAL(Company__c, &apos;doctari Fachpflege&apos;), &apos;HRB 143947&apos;,
IF(ISPICKVAL(Company__c, &apos;doctari Pflege ANÜ&apos;), &apos;HRB 12995&apos;,
&apos;&apos;
)))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Commercial Register</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CommercialRegisterAddition__c</fullName>
        <formula>IF( SeatOfTheSociety__c == &apos;Berlin&apos;, &apos; (Charlottenburg)&apos;, &apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Commercial Register Addition</label>
        <type>Text</type>
    </fields>
</CustomObject>

classes/MarketoAPICalloutBatch.cls
global class MarketoAPICalloutBatch implements Database.Batchable<sObject>, Database.AllowsCallouts{

    Id campaignId;
    CampaignMembersQueryLayer campaignMemberSelector;
    ParserErrorMarketoAPICallout parser;

    global MarketoAPICalloutBatch(Id cId) {
        campaignId = cId;
        campaignMemberSelector = new CampaignMembersQueryLayer();
        parser = new ParserErrorMarketoAPICallout();
    }

    global List<CampaignMember> start(Database.BatchableContext BC) {

        List<CampaignMember> campaignMembers = campaignMemberSelector.getCMBasedOnCampaignIdAndStatus(campaignId);
        return campaignMembers;
    }

    global void execute(Database.BatchableContext BC, List<CampaignMember> scope) {
        String statusString;
        Set<String> marketoIdSet;
        String errorMessageString;
        List<Object> errors;
        Debug__c debug;
        HttpResponse responseToken;
        HttpResponse responseRequestCampaign;

        Campaign campaign = [SELECT Id, Jobportal_Link__c, Campaign_ID__c, Status, Opportunity__c, MarketoAPICallout__c, Subject_Line__c, Email_Body__c, T_MarketoSenderAddress__c FROM Campaign WHERE Id = :campaignId];
        Opportunity opp = [SELECT Id, OwnerId, RecordTypeId FROM Opportunity WHERE Id = :campaign.Opportunity__c];
        User campaignUser = [SELECT Id, Title, FirstName, LastName, Company__c, Street, City, PostalCode, Phone, Fax, Register__c, Email, MobilePhone, SeatOfTheSociety__c, CommercialRegisterAddition__c, CommercialRegister__c FROM User WHERE Id = :opp.OwnerId];
        if (!Test.isRunningTest()) {
            responseToken = MarketoAPICallouts.getTokenCallout();
        } else{
            HttpRequest req = new HttpRequest();
            responseToken = APIAuthCalloutMock.respond(req);
        }

        if (responseToken.getStatusCode() == 200) {

            Map<String, Object> resultT = (Map<String, Object>) JSON.deserializeUntyped(responseToken.getBody());

            String token = resultT.get('access_token').toString();
            String tokenType = resultT.get('token_type').toString();
            String marketoCampaignId;
            String oppTypeLabel = System.Label.Opportunity_Type;
            String recordTypeName = campaign.T_MarketoSenderAddress__c;
            if(recordTypeName == oppTypeLabel){
                //marketoCampaignId = '1200';
                marketoCampaignId = '1047';
            }else{
                //marketoCampaignId = '1200';
                marketoCampaignId = '1135';
            }

            if (!String.isEmpty(token)) {
                
				System.debug('Campaign: ' + campaign);
                MarketoJsonWrapper wrapper = new MarketoJsonWrapper(campaign, scope, campaignUser, null);
                String jsonS = wrapper.SetupJsonString();
                if (!Test.isRunningTest()) {
                    responseRequestCampaign = MarketoAPICallouts.requestCampaign(token, tokenType, jsonS, marketoCampaignId);
                }else{
                    HttpRequest req = new HttpRequest();
                    responseRequestCampaign = APIAuthCalloutMock.respond(req);
                }
                if (responseRequestCampaign.getStatusCode() == 200) {
                    Map<String, Object> resultSecoundCallout = (Map<String, Object>) JSON.deserializeUntyped(responseRequestCampaign.getBody());

                    String success = resultSecoundCallout.get('success').toString();
                    errors = (List<Object>)resultSecoundCallout.get('errors');

                    if (success == 'true') {
                        statusString = 'Sent';
                    }else{
                        if (errors != null) {
                            marketoIdSet = parser.errorMarketoId(errors);
                            statusString = 'Sent';
                        }
                    }
                } else {
                    errorMessageString = responseRequestCampaign.getStatusCode() + ' ' + responseRequestCampaign.getStatus();
                    statusString = 'Cancelled';
                }
            }
        } else {
            errorMessageString = responseToken.getStatusCode() + ' ' + responseToken.getStatus();
            statusString = 'Cancelled';

        }

        for (CampaignMember singleCampaignMember : scope){
            if (marketoIdSet != null) {
                    if(marketoIdSet.contains(singleCampaignMember.Contact.MarketoID__c)){
                        singleCampaignMember.Status = 'Cancelled';
                    }else{
                        singleCampaignMember.Status = statusString;
                    }
            }else {
                singleCampaignMember.Status = statusString;
            }
        }
        if (!String.isEmpty(errorMessageString)) {
            debug = new Debug__c(Message__c = errorMessageString);
            insert debug;
        }
        if (errors != null) {
            for(Object singleError : errors){
                Map<String,Object> error = (Map<String,Object>)singleError;
                String errorString = error.get('message').toString();
                String errorCode = error.get('code').toString();
                debug = new Debug__c(Message__c = errorString, MarketoErrorNumber__c = errorCode);
            }
            insert debug;
        }

        update scope;

    }

    global void finish(Database.BatchableContext BC) {
        List<CampaignMember> campaignMembersCheck = campaignMemberSelector.getCMBasedOnCampaignCheckMarketoId(campaignId);
        List<CampaignMember> campaignMembersSend = campaignMemberSelector.getCMBasedOnCampaignWithStatusSend(campaignId);
        Campaign campaign = [SELECT Id, Status,Jobportal_Link__c, Campaign_ID__c, Opportunity__c, MarketoAPICallout__c,Subject_Line__c, Email_Body__c, T_MarketoSenderAddress__c FROM Campaign WHERE Id = :campaignId];
        Opportunity opp = [SELECT Id, OwnerId, RecordTypeId FROM Opportunity WHERE Id = :campaign.Opportunity__c];
        User campaignUser = [SELECT Id, Title, FirstName, LastName, Company__c, Street, City, PostalCode, Phone, Fax, Register__c, Email, MobilePhone, SeatOfTheSociety__c, CommercialRegisterAddition__c, CommercialRegister__c FROM User WHERE Id = :opp.OwnerId];

        String marketoIdString = System.Label.MarketoTestMailAccounts;
        List<String> marketoCheckIdList = new List<String>();
        Set<String> marketoCheckIdSet = new Set<String>();
        
        Debug__c debug;
        HttpResponse responseToken;
        HttpResponse responseRequestCampaign;

        if (String.isNotBlank(marketoIdString) && marketoIdString.contains(',')) {
            marketoCheckIdList = marketoIdString.split(',');
            marketoCheckIdSet.addAll(marketoCheckIdList);
        }else {
            marketoCheckIdSet.add(marketoIdString);
        }

        if (!Test.isRunningTest()) {
            responseToken = MarketoAPICallouts.getTokenCallout();
        } else{
            HttpRequest req = new HttpRequest();
            responseToken = APIAuthCalloutMock.respond(req);
        }
        if (responseToken.getStatusCode() == 200) {
            Map<String, Object> resultT = (Map<String, Object>) JSON.deserializeUntyped(responseToken.getBody());

            String token = resultT.get('access_token').toString();
            String tokenType = resultT.get('token_type').toString();
            String marketoCampaignId;
            String oppTypeLabel = System.Label.Opportunity_Type;
            String recordTypeName = campaign.T_MarketoSenderAddress__c;
            if(recordTypeName == oppTypeLabel){
                //marketoCampaignId = '1200';
				marketoCampaignId = '1047';
            }else{
                //marketoCampaignId = '1200';
                marketoCampaignId = '1135';
            }


            if (!String.isEmpty(token)) {

                if (String.isNotBlank(marketoIdString)) {
                    System.debug('Campaign: ' + campaign);
                    MarketoJsonWrapper wrapper2 = new MarketoJsonWrapper(campaign, campaignMembersSend, campaignUser, marketoCheckIdSet);
                    String jsonS = wrapper2.SetupJsonForCheckString();

                    if (!Test.isRunningTest()) {
                        responseRequestCampaign = MarketoAPICallouts.requestCampaign(token, tokenType, jsonS, marketoCampaignId);
                    } else {
                        HttpRequest req = new HttpRequest();
                        responseRequestCampaign = APIAuthCalloutMock.respond(req);
                    }
                }
            }
        }else {
            debug = new Debug__c(Message__c =  responseToken.getStatusCode() + ' ' + responseToken.getStatus());
            insert debug;

        }


        if(campaignMembersCheck != null){
            for (CampaignMember singleCampaignMember : campaignMembersCheck){
                if(singleCampaignMember.Contact.HasOptedOutOfEmail = true || String.isEmpty(singleCampaignMember.Contact.MarketoID__c)){
                    singleCampaignMember.Status = 'Cancelled';
                }
            }
            update campaignMembersCheck;
        }
        
        if(campaignMembersCheck != null){
            for (CampaignMember singleCampaignMember : campaignMembersCheck){
                if(singleCampaignMember.Contact.HasOptedOutOfEmail = true || String.isEmpty(singleCampaignMember.Contact.MarketoID__c)){
                    singleCampaignMember.Status = 'Cancelled';
                }
            }
            update campaignMembersCheck;
        }
        if(!campaignMembersSend.isEmpty()){

            campaign.Status = 'Sent';
            campaign.MarketoAPICallout__c = false;

            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

            String[] toAddresses = new String[] {campaignUser.Email};
            mail.setToAddresses(toAddresses);
            mail.setSubject(campaignMembersSend[0].Campaign.Subject_Line__c);
            mail.setHtmlBody('Sehr geehrte/r Anrede Vorname Nachname, <br>'
                    + campaignMembersSend[0].Campaign.Email_Body__c +  ' <br>Job-ID: ' + String.valueOf(campaign.Campaign_ID__c));

            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });


        }else{
            campaign.Status = 'Cancelled';
            campaign.MarketoAPICallout__c = false;
        }
        update campaign;
    }
}