objects/Campaign.object
<CustomObject>
    <sharingModel>FullAccess</sharingModel>
    <fields>
        <fullName>Email_Body__c</fullName>
        <label>Email Body</label>
        <length>4000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Campaign_ID__c</fullName>
        <description>Autonumber for the Campaign. Is used for the better identification of a campaign.
Robin S. 08.04.2019</description>
        <displayFormat>KD{000000}</displayFormat>
        <label>Campaign ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is for the relation between Opp and Campaign.
Robin S. 22.02.2019</description>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Für diese Opportunity kann keine Kampagne erstellt werden</errorMessage>
            <filterItems>
                <field>Opportunity.RecordTypeId</field>
                <operation>equals</operation>
                <value>Substitute Doctor, Substitute Caregiver, Recruitment Doctor, Recruitment Caregiver</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject_Line__c</fullName>
        <description>This is the subject line for the offer mail.
Robin S. 12.04.2019</description>
        <label>Subject Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>T_Sender_Name__c</fullName>
        <formula>IF( Opportunity__r.RecordType.DeveloperName = &quot;SubstituteCaregiver&quot;, &quot;doctari - Pflege Jobs&quot;, &quot;doctari - Aerzte Jobs&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>[T] Sender Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>T_Sender_Address__c</fullName>
        <description>This sender address is used for the offer Mailing via Marketo. 
Robin S. 19.07.2019</description>
        <formula>IF( Opportunity__r.RecordType.DeveloperName = &quot;SubstituteCaregiver&quot;, &quot;pflege@mail.doctari.de&quot;, &quot;aerzte@mail.doctari.de&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>[T] Sender Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MarketoAPICallout__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to start the API Callout Trigger</description>
        <label>MarketoAPICallout</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Email_Body__c</fullName>
        <description>This field is used for the offer mails.
01.04.2019 Robin S.</description>
        <inlineHelpText>Anrede und Grußform werden automatisch erstellt</inlineHelpText>
        <label>Email Body</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Subject_Line__c</fullName>
        <description>This is the subject line for the offer mail.
Robin S. 12.04.2019</description>
        <label>Subject Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/CampaignQueryLayer.cls
/**
 * Created by cristofers on 2020-09-04.
 */

public with sharing class CampaignQueryLayer extends SObjectQueryLayer {
    @TestVisible
    protected override Schema.SObjectType getSObjectType() {
        return Campaign.sObjectType;
    }


    public Campaign getCampaignById (Id campaignId) {
        return [
                SELECT Id, Status, MarketoAPICallout__c, Opportunity__c, T_Sender_Address__c, T_Sender_Name__c, Subject_Line__c, Email_Body__c, Campaign_ID__c, Opportunity__r.Owner.Title, Opportunity__r.Owner.FirstName, Opportunity__r.Owner.LastName, Opportunity__r.Owner.Company__c, Opportunity__r.Owner.Street, Opportunity__r.Owner.City, Opportunity__r.Owner.PostalCode, Opportunity__r.Owner.Phone, Opportunity__r.Owner.Fax, Opportunity__r.Owner.Register__c, Opportunity__r.Owner.Email, Opportunity__r.Owner.MobilePhone, Opportunity__r.Owner.SeatOfTheSociety__c, Opportunity__r.Owner.CommercialRegisterAddition__c, Opportunity__r.Owner.CommercialRegister__c
                FROM Campaign
                WHERE Id  = :campaignId
        ];
    }

}