objects/Campaign.object
<CustomObject>
    <sharingModel>FullAccess</sharingModel>
    <fields>
        <fullName>Email_Body__c</fullName>
        <label>Email Body</label>
        <length>4000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Campaign_ID__c</fullName>
        <description>Autonumber for the Campaign. Is used for the better identification of a campaign.
Robin S. 08.04.2019</description>
        <displayFormat>KD{000000}</displayFormat>
        <label>Campaign ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Subject_Line__c</fullName>
        <description>This is the subject line for the offer mail.
Robin S. 12.04.2019</description>
        <label>Subject Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Jobportal_Link__c</fullName>
        <formula>IF(  PrivateCampaign__c,&quot;Der Job ist nicht veröffentlicht&quot;,IF( CONTAINS(Opportunity__r.RecordType.DeveloperName, &quot;Caregiver&quot;), &quot;https://mein.doctari.de/jobs/&quot; &amp; Campaign_ID__c , &quot;https://mein.doctari.de/jobs/&quot; &amp; Campaign_ID__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Jobportal Link</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>T_MarketoSenderAddress__c</fullName>
        <formula>IF( Opportunity__r.RecordType.DeveloperName = &quot;SubstituteCaregiver&quot;, &quot;pflege@doctari.de&quot;, &quot;aerzte@doctari.de&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>[T]_MarketoSenderAddress</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MarketoID__c</fullName>
        <externalId>true</externalId>
        <label>Marketo ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>doctari</fullName>
                </value>
                <value>
                    <fullName>doctari Ärzte Plus</fullName>
                </value>
                <value>
                    <fullName>doctari Ärzte ANÜ</fullName>
                </value>
                <value>
                    <fullName>doctari Pflege</fullName>
                </value>
                <value>
                    <fullName>doctari Fachpflege</fullName>
                </value>
                <value>
                    <fullName>doctari Pflege ANÜ</fullName>
                </value>
                <value>
                    <fullName>doctari Med ANÜ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SeatOfTheSociety__c</fullName>
        <formula>IF(ISPICKVAL(Company__c, &apos;doctari&apos;) || ISPICKVAL(Company__c, &apos;doctari Ärzte Plus&apos;) || ISPICKVAL(Company__c, &apos;doctari Ärzte ANÜ&apos;) || ISPICKVAL(Company__c, &apos;doctari Med ANÜ&apos;), &apos;Berlin&apos;, 
IF(ISPICKVAL(Company__c, &apos;doctari Pflege&apos;) || ISPICKVAL(Company__c, &apos;doctari Fachpflege&apos;) || ISPICKVAL(Company__c, &apos;doctari Pflege ANÜ&apos;), &apos;Hamburg&apos;, 
&apos;&apos; 
))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Seat of the Society</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CommercialRegister__c</fullName>
        <formula>IF(ISPICKVAL(Company__c, &apos;doctari&apos;), &apos;HRB 146498&apos;,
IF(ISPICKVAL(Company__c, &apos;doctari Ärzte Plus&apos;), &apos;HRB 181928&apos;,
IF(ISPICKVAL(Company__c, &apos;doctari Ärzte ANÜ&apos;), &apos;HRB 152700&apos;,
IF(ISPICKVAL(Company__c, &apos;doctari Med ANÜ&apos;), &apos;HRB 181928&apos;,
IF(ISPICKVAL(Company__c, &apos;doctari Pflege&apos;), &apos;HRB 123378&apos;,
IF(ISPICKVAL(Company__c, &apos;doctari Fachpflege&apos;), &apos;HRB 143947&apos;,
IF(ISPICKVAL(Company__c, &apos;doctari Pflege ANÜ&apos;), &apos;HRB 12995&apos;,
&apos;&apos;
)))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Commercial Register</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CommercialRegisterAddition__c</fullName>
        <formula>IF( SeatOfTheSociety__c == &apos;Berlin&apos;, &apos; (Charlottenburg)&apos;, &apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Commercial Register Addition</label>
        <type>Text</type>
    </fields>
</CustomObject>

classes/MarketoJsonWrapper.cls
/**
 * Created by Cristofer Soler - MaibornWolff GmbH - on 2019-04-01.
 */

public class MarketoJsonWrapper {
    private Campaign campaign;
    private User campaignUser;
    private List<CampaignMember> campaignMembers;
    private Set<String> marketoCheckEmailSet;

    public MarketoJsonWrapper(Campaign c, List<CampaignMember> cmList, User cUser, Set<String> mSet) {
        this.campaign = c;
        this.campaignMembers = cmList;
        this.campaignUser = cUser;
        this.marketoCheckEmailSet = mSet;
		System.debug('Campaign: ' + c);
    }

    public String SetupJsonString(){


        JSONGenerator gen = JSON.createGenerator(true);

        // Write data to the JSON string.
        gen.writeStartObject();
        gen.writeFieldName('input');
        gen.writeStartObject();
        gen.writeFieldName('leads');
        gen.writeStartArray();
        for(CampaignMember singleCampaignMember : campaignMembers){
            if (!String.isEmpty(singleCampaignMember.Contact.MarketoID__c) ) {
                gen.writeStartObject();
                gen.writeNumberField('id', integer.valueof(singleCampaignMember.Contact.MarketoID__c));
                gen.writeEndObject();
            }
        }
        gen.writeEndArray();
        gen.writeFieldName('tokens');
        gen.writeStartArray();
        gen.writeStartObject();
        gen.writeStringField('name', '{{my.Email Subject Line}}');
        gen.writeStringField('value', campaign.Subject_Line__c);
        gen.writeEndObject();
        gen.writeStartObject();
        gen.writeStringField('name', '{{my.Email Body}}');
        gen.writeStringField('value', campaign.Email_Body__c);
        gen.writeEndObject();
		gen.writeStartObject();
        gen.writeStringField('name', '{{my.Email From Address}}');
        gen.writeStringField('value', campaign.T_MarketoSenderAddress__c);
        gen.writeEndObject();
        gen.writeStartObject();
        gen.writeStringField('name', '{{my.User Email}}');
        gen.writeStringField('value', campaignUser.Email);
        gen.writeEndObject();
        gen.writeStartObject();
        gen.writeStringField('name', '{{my.User First Name}}');
        gen.writeStringField('value', campaignUser.FirstName);
        gen.writeEndObject();
        gen.writeStartObject();
        gen.writeStringField('name', '{{my.User Last Name}}');
        gen.writeStringField('value', campaignUser.LastName);
        gen.writeEndObject();
        gen.writeStartObject();
        gen.writeStringField('name', '{{my.User Company}}');
        gen.writeStringField('value', campaignUser.Company__c);
        gen.writeEndObject();
        gen.writeStartObject();
        gen.writeStringField('name', '{{my.User Position}}');
        gen.writeStringField('value', campaignUser.Title);
        gen.writeEndObject();
        gen.writeStartObject();
        gen.writeStringField('name', '{{my.User Address}}');
        gen.writeStringField('value', campaignUser.Street);
        gen.writeEndObject();
        gen.writeStartObject();
        gen.writeStringField('name', '{{my.User Postal Code}}');
        gen.writeStringField('value', campaignUser.PostalCode);
        gen.writeEndObject();
        gen.writeStartObject();
        gen.writeStringField('name', '{{my.User City}}');
        gen.writeStringField('value', campaignUser.City);
        gen.writeEndObject();
        gen.writeStartObject();
        gen.writeStringField('name', '{{my.User Phone}}');
        checkNullValues(gen,'value', campaignUser.Phone);
        gen.writeEndObject();
        gen.writeStartObject();
        gen.writeStringField('name', '{{my.User Mobile}}');
        checkNullValues(gen,'value', campaignUser.MobilePhone);
        gen.writeEndObject();
        gen.writeStartObject();
        gen.writeStringField('name', '{{my.User Fax}}');
        checkNullValues(gen,'value', campaignUser.Fax);
        gen.writeEndObject();
        gen.writeStartObject();
        gen.writeStringField('name', '{{my.Seat Of The Society}}');
        gen.writeStringField('value', campaignUser.SeatOfTheSociety__c);
        gen.writeEndObject();
        gen.writeStartObject();
        gen.writeStringField('name', '{{my.Commercial Register Addition}}');
        checkNullValues(gen,'value', campaignUser.CommercialRegisterAddition__c);
        gen.writeEndObject();
        gen.writeStartObject();
        gen.writeStringField('name', '{{my.Commercial Register}}');
        gen.writeStringField('value', campaignUser.CommercialRegister__c);
        gen.writeEndObject();
        gen.writeStartObject();
        gen.writeStringField('name', '{{my.Campaign ID}}');
        gen.writeStringField('value', campaign.Campaign_ID__c);
        gen.writeEndObject();
        gen.writeStartObject();
        gen.writeStringField('name', '{{my.url}}');
        gen.writeStringField('value', campaign.Jobportal_Link__c);
        gen.writeEndObject();
        gen.writeEndArray();
        gen.writeEndObject();
        gen.writeEndObject();
        String jsonString = gen.getAsString();
        return jsonString;


    }
    
    public String SetupJsonForCheckString(){

        JSONGenerator gen = JSON.createGenerator(true);

        gen.writeStartObject();
        gen.writeFieldName('input');
        gen.writeStartObject();
        gen.writeFieldName('leads');
        gen.writeStartArray();
        for(String marketoId : marketoCheckEmailSet){
            gen.writeStartObject();
            gen.writeNumberField('id', integer.valueof(marketoId));
            gen.writeEndObject();

        }
        
        gen.writeEndArray();
        gen.writeFieldName('tokens');
        gen.writeStartArray();
        gen.writeStartObject();
        gen.writeStringField('name', '{{my.Email Subject Line}}');
        gen.writeStringField('value', campaign.Subject_Line__c);
        gen.writeEndObject();
        gen.writeStartObject();
        gen.writeStringField('name', '{{my.Email Body}}');
        gen.writeStringField('value', campaign.Email_Body__c);
        gen.writeEndObject();
		gen.writeStartObject();
        gen.writeStringField('name', '{{my.Email From Address}}');
        gen.writeStringField('value', campaign.T_MarketoSenderAddress__c);
        gen.writeEndObject();
        gen.writeStartObject();
        gen.writeStringField('name', '{{my.User Email}}');
        gen.writeStringField('value', campaignUser.Email);
        gen.writeEndObject();
        gen.writeStartObject();
        gen.writeStringField('name', '{{my.User First Name}}');
        gen.writeStringField('value', campaignUser.FirstName);
        gen.writeEndObject();
        gen.writeStartObject();
        gen.writeStringField('name', '{{my.User Last Name}}');
        gen.writeStringField('value', campaignUser.LastName);
        gen.writeEndObject();
        gen.writeStartObject();
        gen.writeStringField('name', '{{my.User Company}}');
        gen.writeStringField('value', campaignUser.Company__c);
        gen.writeEndObject();
        gen.writeStartObject();
        gen.writeStringField('name', '{{my.User Position}}');
        gen.writeStringField('value', campaignUser.Title);
        gen.writeEndObject();
        gen.writeStartObject();
        gen.writeStringField('name', '{{my.User Address}}');
        gen.writeStringField('value', campaignUser.Street);
        gen.writeEndObject();
        gen.writeStartObject();
        gen.writeStringField('name', '{{my.User Postal Code}}');
        gen.writeStringField('value', campaignUser.PostalCode);
        gen.writeEndObject();
        gen.writeStartObject();
        gen.writeStringField('name', '{{my.User City}}');
        gen.writeStringField('value', campaignUser.City);
        gen.writeEndObject();
        gen.writeStartObject();
        gen.writeStringField('name', '{{my.User Phone}}');
        checkNullValues(gen,'value', campaignUser.Phone);
        gen.writeEndObject();
        gen.writeStartObject();
        gen.writeStringField('name', '{{my.User Mobile}}');
        checkNullValues(gen,'value', campaignUser.MobilePhone);
        gen.writeEndObject();
        gen.writeStartObject();
        gen.writeStringField('name', '{{my.User Fax}}');
        checkNullValues(gen,'value', campaignUser.Fax);
        gen.writeEndObject();
        gen.writeStartObject();
        gen.writeStringField('name', '{{my.Seat Of The Society}}');
        gen.writeStringField('value', campaignUser.SeatOfTheSociety__c);
        gen.writeEndObject();
        gen.writeStartObject();
        gen.writeStringField('name', '{{my.Commercial Register Addition}}');
        checkNullValues(gen,'value', campaignUser.CommercialRegisterAddition__c);
        gen.writeEndObject();
        gen.writeStartObject();
        gen.writeStringField('name', '{{my.Commercial Register}}');
        gen.writeStringField('value', campaignUser.CommercialRegister__c);
        gen.writeEndObject();
        gen.writeStartObject();
        gen.writeStringField('name', '{{my.Campaign ID}}');
        gen.writeStringField('value', campaign.Campaign_ID__c);
        gen.writeEndObject();
        gen.writeStartObject();
        gen.writeStringField('name', '{{my.url}}');
        gen.writeStringField('value', campaign.Jobportal_Link__c);
        gen.writeEndObject();
        gen.writeEndArray();
        gen.writeEndObject();
        gen.writeEndObject();
        String jsonString = gen.getAsString();
        return jsonString;


    }

    public void checkNullValues(JSONGenerator gen, String fieldName, String fieldValue){
        if(String.isEmpty(fieldValue)){
            gen.writeNullField(fieldName);
        } else{
            gen.writeStringField(fieldName, fieldValue);
        }
    }
}