objects/Campaign.object
<CustomObject>
    <sharingModel>FullAccess</sharingModel>
    <fields>
        <fullName>Email_Body__c</fullName>
        <label>Email Body</label>
        <length>4000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Campaign_ID__c</fullName>
        <description>Autonumber for the Campaign. Is used for the better identification of a campaign.
Robin S. 08.04.2019</description>
        <displayFormat>KD{000000}</displayFormat>
        <label>Campaign ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Subject_Line__c</fullName>
        <description>This is the subject line for the offer mail.
Robin S. 12.04.2019</description>
        <label>Subject Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>aktiv</fullName>
                    <default>true</default>
                    <label>aktiv</label>
                </value>
                <value>
                    <fullName>inaktiv</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Debug__c.object
<CustomObject>
    <description>This object lists all exception errors for Apex Error Exceptions.</description>
    <label>Debug</label>
    <nameField>
        <displayFormat>DB-{00000}</displayFormat>
        <label>Debug Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debugs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Message__c</fullName>
        <description>The error message in case there was an exception.</description>
        <label>Message</label>
        <length>130000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Debugs</relationshipLabel>
        <relationshipName>Debugs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ErrorCode__c</fullName>
        <label>ErrorCode</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CampaignmemberIds__c</fullName>
        <label>CampaignmemberIds</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

classes/StatusHandler.cls
/**
 * Created by cristofers on 2020-09-07.
 */

public with sharing class StatusHandler {

    private static String CANCELLED = 'Cancelled';
    private static String SENT = 'Sent';
    private static String SUCCESSRESULT = 'success';
    private static String ERRORSRESULT = 'errorcode';
    private static String CODE = 'code';
    private static String INAKTIV = 'Inaktiv';
    private static String RESPONSES = 'responses';
    private static String MESSAGEKEY = 'messageKey';
    private static String MESSAGE = 'message';

    String statusString;
    Set<Id> camapignmemberIdSetSent;
    Set<Id> camapignmemberIdSetCancelled;



    public List<CampaignMember> getStatusCampaignMembers(HttpResponse responseRequestCampaign, List<CampaignMember> campaignMembers, Campaign campaign){

        List<Object> errors;
        List<Object> response;
        List<Debug__c> debugs = new List<Debug__c>();
        String errorMessageString;
        camapignmemberIdSetSent = new Set<Id>();
        camapignmemberIdSetCancelled = new Set<Id>();

        if (responseRequestCampaign.getStatusCode() == 202) {
            Map<String, Object> resultSecoundCallout = (Map<String, Object>) JSON.deserializeUntyped(responseRequestCampaign.getBody());
            
            response = (List<Object>)resultSecoundCallout.get(RESPONSES);
            

            for (Object obj : response) {
                Map<String, Object> responseResult = (Map<String, Object>)obj;
                if (responseResult.keyset().contains(ERRORSRESULT)) {
                    camapignmemberIdSetCancelled.add((Id)responseResult.get(MESSAGEKEY));
                    Integer error = (Integer)responseResult.get(ERRORSRESULT);
                    String errorMessage = (String)responseResult.get(MESSAGE);
                    debugs.add(new Debug__c(ErrorCode__c = error, Message__c = errorMessage, Campaign__c = campaign.Id, CampaignmemberIds__c = (String)responseResult.get(MESSAGEKEY)));
                }else {
                    camapignmemberIdSetSent.add((Id)responseResult.get(MESSAGEKEY));
                }
            }
            if (debugs != null && !debugs.isEmpty()) {
                insert debugs;
            }

        } else {
            camapignmemberIdSetCancelled.addAll((new Map<Id,CampaignMember>(campaignMembers)).keySet());
            errorMessageString = responseRequestCampaign.getStatusCode() + ' ' + responseRequestCampaign.getStatus();
            addDebug(errorMessageString, errors,campaign.Id, camapignmemberIdSetCancelled);
        }

        List<CampaignMember> cmWithStatusUpdate = setStatusCampaignMembers(campaignMembers);

        return cmWithStatusUpdate;

    }

    public List<CampaignMember> setStatusCampaignMembers(List<CampaignMember> campaignMembers){

        for (CampaignMember singleCampaignMember : campaignMembers){
            if (camapignmemberIdSetCancelled.contains(singleCampaignMember.Id)) {
                singleCampaignMember.Status = CANCELLED;
            } else if (camapignmemberIdSetSent.contains(singleCampaignMember.Id)) {
                singleCampaignMember.Status = SENT;
            } 
        }
        return campaignMembers;

    }

    public void setStatusCampaignMemberCheck(List<CampaignMember> campaignMembersCheck){

        for (CampaignMember singleCampaignMember : campaignMembersCheck){
            if(singleCampaignMember.Contact.HasOptedOutOfEmail = true || singleCampaignMember.Contact.Status__c == INAKTIV){
                singleCampaignMember.Status = CANCELLED;
            }
        }
        update campaignMembersCheck;

    }

    public Campaign setCampaignStatus(List<CampaignMember> campaignMembersSend, Campaign campaign, User user){
        if(campaignMembersSend != null && !campaignMembersSend.isEmpty()){

            campaign.Status = SENT;

            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

            String[] toAddresses = new String[] {user.Email};
            mail.setToAddresses(toAddresses);
            mail.setSubject(campaignMembersSend[0].Campaign.Subject_Line__c);
            mail.setHtmlBody('Sehr geehrte/r Anrede Vorname Nachname, <br>'
                    + campaignMembersSend[0].Campaign.Email_Body__c +  ' <br>Job-ID: ' + String.valueOf(campaign.Campaign_ID__c));

            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        }else{
            campaign.Status = CANCELLED;
        }

        return campaign;
    }

    public void setPreCampaignStatusSent(Map<Id, List<CampaignMember>> campaignMembersSendMap, List<Campaign> campaigns){

        for (Campaign singleCampaign : campaigns){
            if (campaignMembersSendMap.get(singleCampaign.Id) != null) {
                    singleCampaign.Status = SENT;

            }
        }
        update campaigns;

    }

    public void setPreCampaignStatusCancelled(List<Campaign> campaigns){

        for (Campaign singleCampaign : campaigns){
            singleCampaign.Status = CANCELLED;
        }
        update campaigns;

    }

    public void setPreCampaignMemberStatusCancelled(Map<Id, List<CampaignMember>> campaignMembersSendMap, List<Campaign> campaigns){

        List<CampaignMember> cmList;
        for(Campaign singleCampaign : campaigns){
            cmList = campaignMembersSendMap.get(singleCampaign.Id);
            singleCampaign.Status = CANCELLED;
            if (cmList != null && !cmList.isEmpty()) {
                for(CampaignMember singleCampaignMember : cmList){
                    singleCampaignMember.Status = CANCELLED;
                }
            }

        }
        update cmList;
        
    }

    public void addDebug(String errorMessageString, List<Object> errors, Id campaignId, Set<Id> campaignMembersIdSet){
        Debug__c debug;

        if (!String.isEmpty(errorMessageString)) {
            debug = new Debug__c(Message__c = errorMessageString, Campaign__c = campaignId, CampaignmemberIds__c = campaignMembersIdSet.toString());
            insert debug;
        }
    }
}