objects/Contract.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Shows the Relation between Quote and Contract.
Robin S. 15.10.2019</description>
        <inlineHelpText>Referenz zum verbundenen Vertragsentwurf</inlineHelpText>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Reisekosten__c.object
<CustomObject>
    <label>Reisekosten</label>
    <nameField>
        <label>Reisekosten Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reisekosten</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Traveling Costs</relationshipLabel>
        <relationshipName>Traveling_Costs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Traveling Costs</relationshipLabel>
        <relationshipName>Traveling_Costs</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Unterkunftsbuchung__c.object
<CustomObject>
    <label>Unterkunftsbuchung</label>
    <nameField>
        <displayFormat>U-{0000}</displayFormat>
        <label>Unterkunftsbuchungs Nummer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unterkunftsbuchungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Haustier__c</fullName>
        <label>Haustier</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ja</fullName>
                </value>
                <value>
                    <fullName>Nein</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Abreisetag__c</fullName>
        <label>Abreisetag</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Anreisetag__c</fullName>
        <label>Anreisetag</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Reisekosten__c</fullName>
        <label>Reisekosten</label>
        <referenceTo>Reisekosten__c</referenceTo>
        <relationshipLabel>Unterkunftsbuchungen</relationshipLabel>
        <relationshipName>Unterkunftsbuchungen</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Anzahl_Zimmer__c</fullName>
        <label>Anzahl Zimmer</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sonderwuensche__c</fullName>
        <label>Sonderwünsche</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Anzahl_Personen__c</fullName>
        <label>Anzahl Personen</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>max_Preis_pro_Nacht__c</fullName>
        <label>max. Preis pro Nacht</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Kostentraeger_Klinik__c</fullName>
        <label>Kostenträger Klinik</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Parkplatz_erwuenscht__c</fullName>
        <label>Parkplatz erwünscht?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>keine Info</fullName>
                    <default>true</default>
                    <label>keine Info</label>
                </value>
                <value>
                    <fullName>Ja</fullName>
                </value>
                <value>
                    <fullName>Nein</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Kostentraeger_doctari__c</fullName>
        <label>Kostenträger doctari</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Verpflegung_erwuenscht__c</fullName>
        <label>Verpflegung erwünscht?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Nein</fullName>
                    <default>true</default>
                    <label>Nein</label>
                </value>
                <value>
                    <fullName>Ja</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Kochgelegenheit_gew_nscht__c</fullName>
        <description>SFC-2231</description>
        <label>Kochgelegenheit gewünscht</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ja</fullName>
                </value>
                <value>
                    <fullName>nein</fullName>
                </value>
                <value>
                    <fullName>keine Info</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Kostentraeger_Mitarbeiter__c</fullName>
        <label>Kostenträger Mitarbeiter</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rechnung_wird_bezahlt_von__c</fullName>
        <label>Rechnung wird bezahlt von</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mitarbeiter</fullName>
                </value>
                <value>
                    <fullName>doctari</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>benoetigte_Unterkunftstage__c</fullName>
        <label>benötigte Unterkunftstage</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Entfernung_Klinik_Unterkunft_max__c</fullName>
        <label>Entfernung Klinik - Unterkunft max.</label>
        <length>80</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/ReisekostenQueryLayer.cls
public class ReisekostenQueryLayer extends SObjectQueryLayer {
    @TestVisible
    protected override Schema.SObjectType getSObjectType() {
            return Reisekosten__c.sObjectType;
    }

    
    @AuraEnabled(Cacheable=true)
    public static List<Reisekosten__c> getReisekostenFromQ(String recordId) {
            return [
                    SELECT Id, Quote__c, Contract__c, Contract__r.Status,
                         (Select id, Abreisetag__c, Anreisetag__c, Anzahl_Personen__c, Anzahl_Zimmer__c, Entfernung_Klinik_Unterkunft_max__c, Haustier__c, Kostentraeger_doctari__c, Kostentraeger_Klinik__c, Kostentraeger_Mitarbeiter__c, max_Preis_pro_Nacht__c, Parkplatz_erwuenscht__c, Rechnung_wird_bezahlt_von__c, Sonderwuensche__c, Verpflegung_erwuenscht__c, benoetigte_Unterkunftstage__c, Kochgelegenheit_gew_nscht__c FROM Unterkunftsbuchungen__r)
                    FROM Reisekosten__c
                   WHERE (Quote__c = :recordId OR Contract__c = : recordId)
            ];
            
    }
}