objects/Opportunity.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Reisekosten__c</fullName>
        <label>Reisekosten</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Reisekosten</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

objects/Reisekosten__c.object
<CustomObject>
    <label>Reisekosten</label>
    <nameField>
        <label>Reisekosten Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reisekosten</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Reisekosten</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

objects/Reisekosten_Art__c.object
<CustomObject>
    <label>Reisekosten Art</label>
    <nameField>
        <displayFormat>RA-{0000}</displayFormat>
        <label>Reisekosten Art Nummer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reisekosten Arten</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Reisekosten__c</fullName>
        <label>Reisekosten</label>
        <referenceTo>Reisekosten__c</referenceTo>
        <relationshipLabel>Reisekosten Arten</relationshipLabel>
        <relationshipName>Reisekosten_Arten</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

classes/RKlwcControllerTest.cls
@isTest
public class RKlwcControllerTest {
   
    
    @IsTest
    static void deleteTest(){
        ReisekostenArtQueryLayer layer = new ReisekostenArtQueryLayer();
        ReisekostenQueryLayer layer2 = new ReisekostenQueryLayer();
        RKlwcController controller = new RKlwcController();
        Account acc = SObjectFactory.generateInstitutAccount();
        acc.Name = 'TestAcc1';
        INSERT acc;
        Contact con = SObjectFactory.generateContact(acc);
        INSERT con;
        Account pacc = SObjectFactory.generatePersonAccount();
        INSERT pacc;
        Opportunity opp =  SObjectFactory.generateOpportunity2(acc, con);
        INSERT opp;
        Quote quote = SObjectFactory.generateQuote(pacc,acc, opp);
        INSERT quote;
        Reisekosten__c rk = SObjectFactory.generateReisekosten(acc, opp, quote);
        rk.Category__c = 'Unterkunft';
        INSERT rk;
        Reisekosten_Art__c rkArt = SObjectFactory.generateReisekostenArt(rk);
        INSERT rkArt;
        sObjectType oType =  layer.getSObjectType();
        sObjectType oType2 =  layer2.getSObjectType();
        List<Reisekosten__c> rkListBefor = ReisekostenQueryLayer.getReisekostenFromQ(quote.Id);
        List<Reisekosten_Art__c> rkArtListBefor = ReisekostenArtQueryLayer.getReisekostenArtenFromRK(quote.Id, 'Doctor/Caregiver', 'Unterkunft');
        Test.startTest();
        RKlwcController.deleteRecords(quote.Id, 'Unterkunft');
        RKlwcController.deleteRecords('', '');
        Test.stopTest();
        List<Reisekosten_Art__c> rkArtListAfter = ReisekostenArtQueryLayer.getReisekostenArtenFromRK(quote.Id, 'Doctor/Caregiver', 'Unterkunft');
        System.assert(rkListBefor.size() >  0);
        System.assert(rkArtListBefor.size() > 0);
        System.assert(rkArtListAfter.size() < 1);
    }


}