objects/Reisekosten__c.object
<CustomObject>
    <label>Reisekosten</label>
    <nameField>
        <label>Reisekosten Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reisekosten</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Reisekosten</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Traveling Costs</relationshipLabel>
        <relationshipName>Traveling_Costs</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

classes/RKlwcController.cls
public with sharing class RKlwcController {
    
    @AuraEnabled
    public static void deleteRecords(String recordId, String cString){
        List<Reisekosten__c> rkList = new List<Reisekosten__c>();
        rkList = [SELECT Id, Category__c, Contract__c FROM Reisekosten__c WHERE Category__c = : cString AND Contract__c = : recordId];
        if(rkList.size()> 0){
            try {
                delete rkList;
            } catch (Exception ex) {
                throw new AuraHandledException(ex.getMessage());
            }
        }

    }

}