objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>doctari</fullName>
                </value>
                <value>
                    <fullName>doctari Ärzte Plus</fullName>
                </value>
                <value>
                    <fullName>doctari Ärzte ANÜ</fullName>
                </value>
                <value>
                    <fullName>doctari Pflege</fullName>
                </value>
                <value>
                    <fullName>doctari Fachpflege</fullName>
                </value>
                <value>
                    <fullName>doctari Pflege ANÜ</fullName>
                </value>
                <value>
                    <fullName>doctari Med ANÜ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Register__c</fullName>
        <description>This field is used for the offer Mailing via Marketo. 
Robin S. 11.04.2019</description>
        <formula>IF(City=&quot;Hamburg&quot;, &quot;Amtsgericht Hamburg, HRB 123378 Sitz der Gesellschaft: Hamburg&quot;, &quot;Amtsgericht Berlin (Charlottenburg), HRB 146498 Sitz der Gesellschaft: Berlin&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Register</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeatOfTheSociety__c</fullName>
        <formula>IF(ISPICKVAL(Company__c, &apos;doctari&apos;) || ISPICKVAL(Company__c, &apos;doctari Ärzte Plus&apos;) || ISPICKVAL(Company__c, &apos;doctari Ärzte ANÜ&apos;) || ISPICKVAL(Company__c, &apos;doctari Med ANÜ&apos;), &apos;Berlin&apos;, 
IF(ISPICKVAL(Company__c, &apos;doctari Pflege&apos;) || ISPICKVAL(Company__c, &apos;doctari Fachpflege&apos;) || ISPICKVAL(Company__c, &apos;doctari Pflege ANÜ&apos;), &apos;Hamburg&apos;, 
&apos;&apos; 
))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Seat of the Society</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CommercialRegister__c</fullName>
        <formula>IF(ISPICKVAL(Company__c, &apos;doctari&apos;), &apos;HRB 146498&apos;,
IF(ISPICKVAL(Company__c, &apos;doctari Ärzte Plus&apos;), &apos;HRB 181928&apos;,
IF(ISPICKVAL(Company__c, &apos;doctari Ärzte ANÜ&apos;), &apos;HRB 152700&apos;,
IF(ISPICKVAL(Company__c, &apos;doctari Med ANÜ&apos;), &apos;HRB 181928&apos;,
IF(ISPICKVAL(Company__c, &apos;doctari Pflege&apos;), &apos;HRB 123378&apos;,
IF(ISPICKVAL(Company__c, &apos;doctari Fachpflege&apos;), &apos;HRB 143947&apos;,
IF(ISPICKVAL(Company__c, &apos;doctari Pflege ANÜ&apos;), &apos;HRB 12995&apos;,
&apos;&apos;
)))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Commercial Register</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CommercialRegisterAddition__c</fullName>
        <formula>IF( SeatOfTheSociety__c == &apos;Berlin&apos;, &apos; (Charlottenburg)&apos;, &apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Commercial Register Addition</label>
        <type>Text</type>
    </fields>
</CustomObject>

classes/UserQueryLayer.cls
/**
 * Created by cristofers on 2019-09-24.
 */

public with sharing class UserQueryLayer /*extends SObjectQueryLayer */{
       /* @TestVisible
        protected override Schema.SObjectType getSObjectType() {
            return User.sObjectType;
        }
        public User getUserByOpp (Id userId) {
            return [
                    SELECT Id, Title, FirstName, LastName, Company__c, Street, City, PostalCode, Phone, Fax, Register__c, Email, MobilePhone, SeatOfTheSociety__c, CommercialRegisterAddition__c, CommercialRegister__c
                    FROM User
                    WHERE Id = :userId
                    LIMIT 1
            ];
        }*/

}